/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : Generated artifact
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE ETL_RECONCILIATION_LOG (
    LOG_ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    PIPELINE_NAME       VARCHAR(100)    NOT NULL,
    RUN_TIMESTAMP       TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    LOAD_TYPE           VARCHAR(20),
    SOURCE_COUNT        NUMBER(18,0),
    INSERTED_COUNT      NUMBER(18,0),
    UPDATED_COUNT       NUMBER(18,0),
    DELETED_COUNT       NUMBER(18,0),
    EXCLUDED_COUNT      NUMBER(18,0),
    DEDUP_COUNT         NUMBER(18,0),
    STATUS              VARCHAR(20),
    ERROR_MESSAGE       VARCHAR(4000),
    LAST_UPDATED_AT     TIMESTAMP_NTZ,
    RUN_START_TS        TIMESTAMP_NTZ,
    RUN_END_TS          TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
-- PK defined inline via AUTOINCREMENT PRIMARY KEY above.

-- SECTION 3: Notes
-- One row per SP execution. STATUS: SUCCESS / FAILED.
-- LOAD_TYPE: FULL or INCREMENTAL.
-- LAST_UPDATED_AT: max UPDATED_AT from source batch; used as watermark for next run.