/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : ETL reconciliation log DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS ETL_RECONCILIATION_LOG (
    RUN_ID               VARCHAR(100)    NOT NULL,
    RUN_TIMESTAMP        TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    LOAD_TYPE            VARCHAR(20),
    SOURCE_COUNT         NUMBER(12,0),
    FILTERED_COUNT       NUMBER(12,0),
    DEDUP_COUNT          NUMBER(12,0),
    INSERT_COUNT         NUMBER(12,0),
    UPDATE_COUNT         NUMBER(12,0),
    SOFT_DELETE_COUNT    NUMBER(12,0),
    TARGET_COUNT         NUMBER(12,0),
    LAST_RUN_TIMESTAMP   TIMESTAMP_NTZ,
    CURRENT_WATERMARK    TIMESTAMP_NTZ,
    STATUS               VARCHAR(20),
    ERROR_MESSAGE        VARCHAR(2000),
    DURATION_SECONDS     NUMBER(10,2)
);

-- SECTION 2: Constraints
ALTER TABLE ETL_RECONCILIATION_LOG
    ADD CONSTRAINT IF NOT EXISTS PK_RECON_LOG PRIMARY KEY (RUN_ID);

-- SECTION 3: Notes
-- RUN_ID          : UUID generated per execution via UUID_STRING()
-- LOAD_TYPE       : 'FULL' on first run, 'INCREMENTAL' on subsequent runs
-- LAST_RUN_TIMESTAMP / CURRENT_WATERMARK: support watermark chain for incremental logic
-- STATUS          : 'SUCCESS' | 'FAILED'