/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_SOURCE
Purpose     : Generated artifact
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE AEROSPACE_PARTS_SOURCE (
    PART_NUMBER         VARCHAR(50)     NOT NULL,
    PART_NAME           VARCHAR(200),
    MANUFACTURER        VARCHAR(200),
    CATEGORY            VARCHAR(100),
    LIFECYCLE_STATUS    VARCHAR(50),
    CERTIFICATION_STATUS VARCHAR(50),
    INSTALLATION_DATE   DATE,
    LEAD_TIME_DAYS      NUMBER(10,0),
    WEIGHT_KG           NUMBER(18,4),
    UNIT_PRICE_USD      NUMBER(18,4),
    STOCK_QUANTITY      NUMBER(10,0),
    SUPPLIER_ID         VARCHAR(50),
    WAREHOUSE_LOCATION  VARCHAR(100),
    UPDATED_AT          TIMESTAMP_NTZ   NOT NULL,
    CREATED_AT          TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
ALTER TABLE AEROSPACE_PARTS_SOURCE ADD CONSTRAINT UQ_SRC_PART_NUMBER UNIQUE (PART_NUMBER, UPDATED_AT);

-- SECTION 3: Notes
-- Business key: PART_NUMBER. UPDATED_AT drives incremental load and deduplication.
-- CERTIFICATION_STATUS valid values: Pending, FAA, EASA, Dual.
-- LIFECYCLE_STATUS valid values: Active, End of Life, Decommissioned.