/*=========================================================
Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
-- SECTION 1: Variables

    v_run_start_ts      TIMESTAMP_NTZ;
    v_run_end_ts        TIMESTAMP_NTZ;
    v_source_count      INTEGER DEFAULT 0;
    v_inserted_count    INTEGER DEFAULT 0;
    v_updated_count     INTEGER DEFAULT 0;
    v_deleted_count     INTEGER DEFAULT 0;
    v_dedup_count       INTEGER DEFAULT 0;
    v_excluded_count    INTEGER DEFAULT 0;
    v_status            VARCHAR DEFAULT 'SUCCESS';
    v_error_message     VARCHAR DEFAULT NULL;
    v_pipeline_name     VARCHAR DEFAULT 'SP_LOAD_AEROSPACE_PARTS_SCD1';
    v_load_type         VARCHAR DEFAULT 'SCD1_INCREMENTAL';

BEGIN
    -- -------------------------------------------------------------------------
    -- STEP 0: Capture run start timestamp
    -- -------------------------------------------------------------------------
    v_run_start_ts := CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ;

    -- -------------------------------------------------------------------------
    -- STEP 1: Create deduplicated staging CTE as a temp table
    --         Keep only the latest record per PART_NUMBER based on UPDATED_AT
    -- -------------------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_DEDUP_AEROSPACE AS
    WITH RANKED AS (
        -- SECTION 2: Source Processing
SELECT
            CATEGORY,
            CERTIFICATION_STATUS,
            CREATED_AT,
            INSTALLATION_DATE,
            LEAD_TIME_DAYS,
            LIFECYCLE_STATUS,
            MANUFACTURER,
            PART_NAME,
            PART_NUMBER,
            STOCK_QUANTITY,
            SUPPLIER_ID,
            UNIT_PRICE_USD,
            UPDATED_AT,
            WAREHOUSE_LOCATION,
            WEIGHT_KG,
            ROW_NUMBER() OVER (
                PARTITION BY PART_NUMBER
                ORDER BY UPDATED_AT DESC NULLS LAST
            ) AS RN
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE PART_NUMBER IS NOT NULL
    )
    SELECT
        CATEGORY,
        CERTIFICATION_STATUS,
        CREATED_AT,
        INSTALLATION_DATE,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        MANUFACTURER,
        PART_NAME,
        PART_NUMBER,
        STOCK_QUANTITY,
        SUPPLIER_ID,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WAREHOUSE_LOCATION,
        WEIGHT_KG
    FROM RANKED
    WHERE RN = 1;

    -- -------------------------------------------------------------------------
    -- STEP 2: Capture source count (pre-dedup) and dedup count
    -- -------------------------------------------------------------------------
    SELECT COUNT(*)
    INTO :v_source_count
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    WHERE PART_NUMBER IS NOT NULL;

    -- Excluded count = records with NULL PART_NUMBER (excluded from processing)
    SELECT COUNT(*)
    INTO :v_excluded_count
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    WHERE PART_NUMBER IS NULL;

    -- Dedup count = total source valid rows minus deduplicated rows
    SELECT (:v_source_count - COUNT(*))
    INTO :v_dedup_count
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_DEDUP_AEROSPACE;

    -- -------------------------------------------------------------------------
    -- STEP 3: Apply transformation rules into a transformed temp table
    --         - MANUFACTURER: uppercase
    --         - WEIGHT_KG: set to NULL -- SECTION 3: Data Validation
if INSTALLATION_DATE is older than 2 years
    --         - RISK_SCORE: derived from CERTIFICATION_STATUS and LEAD_TIME_DAYS
    --           Logic:
    --             CERTIFICATION_STATUS = 'NOT_CERTIFIED'                  => 3 (High Risk)
    --             CERTIFICATION_STATUS = 'PENDING' AND LEAD_TIME_DAYS > 30 => 2 (Medium Risk)
    --             CERTIFICATION_STATUS = 'CERTIFIED' AND LEAD_TIME_DAYS <= 30 => 1 (Low Risk)
    --             All other combinations                                   => 2 (Medium Risk)
    -- -------------------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_TRANSFORMED_AEROSPACE AS
    SELECT
        CATEGORY,
        CERTIFICATION_STATUS,
        CREATED_AT,
        INSTALLATION_DATE,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        UPPER(MANUFACTURER)                                         AS MANUFACTURER,
        PART_NAME,
        PART_NUMBER,
        STOCK_QUANTITY,
        SUPPLIER_ID,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WAREHOUSE_LOCATION,
        CASE
            WHEN INSTALLATION_DATE IS NOT NULL
             AND DATEDIFF('year', INSTALLATION_DATE::DATE, CURRENT_DATE()) >= 2
            THEN NULL
            ELSE WEIGHT_KG
        END                                                         AS WEIGHT_KG,
        CASE
            WHEN UPPER(TRIM(CERTIFICATION_STATUS)) = 'NOT_CERTIFIED'
                THEN 3
            WHEN UPPER(TRIM(CERTIFICATION_STATUS)) = 'PENDING'
             AND LEAD_TIME_DAYS > 30
                THEN 2
            WHEN UPPER(TRIM(CERTIFICATION_STATUS)) = 'CERTIFIED'
             AND LEAD_TIME_DAYS <= 30
                THEN 1
            ELSE 2
        END                                                         AS RISK_SCORE
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_DEDUP_AEROSPACE;

    -- -------------------------------------------------------------------------
    -- STEP 4: SCD Type 1 -- SECTION 4: Merge Logic
MERGE into AEROSPACE_PARTS_TARGET
    --         Business Key: PART_NUMBER
    --         On MATCH    : Update all non-key columns (overwrite - SCD1)
    --         On NOT MATCH: Insert new record
    -- -------------------------------------------------------------------------
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS TGT
    USING GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_TRANSFORMED_AEROSPACE AS SRC
        ON TGT.PART_NUMBER = SRC.PART_NUMBER
    WHEN MATCHED
     AND (
            NVL(TGT.CATEGORY,              '~~NULL~~') <> NVL(SRC.CATEGORY,              '~~NULL~~') OR
            NVL(TGT.CERTIFICATION_STATUS,  '~~NULL~~') <> NVL(SRC.CERTIFICATION_STATUS,  '~~NULL~~') OR
            NVL(TGT.INSTALLATION_DATE::VARCHAR, '~~NULL~~') <> NVL(SRC.INSTALLATION_DATE::VARCHAR, '~~NULL~~') OR
            NVL(TGT.LEAD_TIME_DAYS,        -9999)      <> NVL(SRC.LEAD_TIME_DAYS,        -9999)      OR
            NVL(TGT.LIFECYCLE_STATUS,      '~~NULL~~') <> NVL(SRC.LIFECYCLE_STATUS,      '~~NULL~~') OR
            NVL(TGT.MANUFACTURER,          '~~NULL~~') <> NVL(SRC.MANUFACTURER,          '~~NULL~~') OR
            NVL(TGT.PART_NAME,             '~~NULL~~') <> NVL(SRC.PART_NAME,             '~~NULL~~') OR
            NVL(TGT.STOCK_QUANTITY,        -9999)      <> NVL(SRC.STOCK_QUANTITY,        -9999)      OR
            NVL(TGT.SUPPLIER_ID,           '~~NULL~~') <> NVL(SRC.SUPPLIER_ID,           '~~NULL~~') OR
            NVL(TGT.UNIT_PRICE_USD,        -9999)      <> NVL(SRC.UNIT_PRICE_USD,        -9999)      OR
            NVL(TGT.UPDATED_AT::VARCHAR,   '~~NULL~~') <> NVL(SRC.UPDATED_AT::VARCHAR,   '~~NULL~~') OR
            NVL(TGT.WAREHOUSE_LOCATION,    '~~NULL~~') <> NVL(SRC.WAREHOUSE_LOCATION,    '~~NULL~~') OR
            NVL(TGT.WEIGHT_KG,             -9999)      <> NVL(SRC.WEIGHT_KG,             -9999)      OR
            NVL(TGT.RISK_SCORE,            -9999)      <> NVL(SRC.RISK_SCORE,            -9999)
         )
    THEN UPDATE SET
        TGT.CATEGORY             = SRC.CATEGORY,
        TGT.CERTIFICATION_STATUS = SRC.CERTIFICATION_STATUS,
        TGT.CREATED_AT           = SRC.CREATED_AT,
        TGT.INSTALLATION_DATE    = SRC.INSTALLATION_DATE,
        TGT.LEAD_TIME_DAYS       = SRC.LEAD_TIME_DAYS,
        TGT.LIFECYCLE_STATUS     = SRC.LIFECYCLE_STATUS,
        TGT.LOAD_TIMESTAMP       = CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
        TGT.MANUFACTURER         = SRC.MANUFACTURER,
        TGT.PART_NAME            = SRC.PART_NAME,
        TGT.RISK_SCORE           = SRC.RISK_SCORE,
        TGT.STOCK_QUANTITY       = SRC.STOCK_QUANTITY,
        TGT.SUPPLIER_ID          = SRC.SUPPLIER_ID,
        TGT.UNIT_PRICE_USD       = SRC.UNIT_PRICE_USD,
        TGT.UPDATED_AT           = SRC.UPDATED_AT,
        TGT.WAREHOUSE_LOCATION   = SRC.WAREHOUSE_LOCATION,
        TGT.WEIGHT_KG            = SRC.WEIGHT_KG
    WHEN NOT MATCHED THEN INSERT (
        CATEGORY,
        CERTIFICATION_STATUS,
        CREATED_AT,
        INSTALLATION_DATE,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        LOAD_TIMESTAMP,
        MANUFACTURER,
        PART_NAME,
        PART_NUMBER,
        RISK_SCORE,
        STOCK_QUANTITY,
        SUPPLIER_ID,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WAREHOUSE_LOCATION,
        WEIGHT_KG
    ) VALUES (
        SRC.CATEGORY,
        SRC.CERTIFICATION_STATUS,
        SRC.CREATED_AT,
        SRC.INSTALLATION_DATE,
        SRC.LEAD_TIME_DAYS,
        SRC.LIFECYCLE_STATUS,
        CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
        SRC.MANUFACTURER,
        SRC.PART_NAME,
        SRC.PART_NUMBER,
        SRC.RISK_SCORE,
        SRC.STOCK_QUANTITY,
        SRC.SUPPLIER_ID,
        SRC.UNIT_PRICE_USD,
        SRC.UPDATED_AT,
        SRC.WAREHOUSE_LOCATION,
        SRC.WEIGHT_KG
    );

    -- -------------------------------------------------------------------------
    -- STEP 5: Capture MERGE row counts from MERGE statement
    -- -------------------------------------------------------------------------
    -- Snowflake does not expose per-action counts directly after MERGE;
    -- derive inserted and updated counts by comparing target state.
    SELECT
        SUM(CASE WHEN TGT.LOAD_TIMESTAMP = TGT.UPDATED_AT_LOAD AND TGT.CREATED_AT_LOAD = TGT.LOAD_TIMESTAMP THEN 1 ELSE 0 END)
    INTO :v_inserted_count
    FROM (
        SELECT
            LOAD_TIMESTAMP,
            LOAD_TIMESTAMP AS UPDATED_AT_LOAD,
            LOAD_TIMESTAMP AS CREATED_AT_LOAD
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
        WHERE LOAD_TIMESTAMP >= :v_run_start_ts
    ) TGT;

    -- Use MERGE row counts via system approach: count newly loaded rows
    SELECT COUNT(*)
    INTO :v_inserted_count
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    WHERE LOAD_TIMESTAMP >= :v_run_start_ts
      AND CREATED_AT IS NOT NULL;

    -- Approximate updated count = deduplicated source rows that matched target
    SELECT COUNT(*)
    INTO :v_updated_count
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_TRANSFORMED_AEROSPACE SRC
    INNER JOIN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET TGT
        ON SRC.PART_NUMBER = TGT.PART_NUMBER
    WHERE TGT.LOAD_TIMESTAMP >= :v_run_start_ts;

    -- Inserted = total rows loaded this run minus updated rows
    v_inserted_count := v_inserted_count - v_updated_count;
    IF (v_inserted_count < 0) THEN
        v_inserted_count := 0;
    END IF;

    -- -------------------------------------------------------------------------
    -- STEP 6: Soft-delete handling
    --         Records in TARGET that are NOT in SOURCE (by PART_NUMBER)
    --         and not already 'Decommissioned' => mark LIFECYCLE_STATUS = 'Decommissioned'
    -- -------------------------------------------------------------------------
    UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET TGT
    SET
        TGT.LIFECYCLE_STATUS = 'Decommissioned',
        TGT.LOAD_TIMESTAMP   = CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
    WHERE TGT.PART_NUMBER NOT IN (
            SELECT PART_NUMBER
            FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_TRANSFORMED_AEROSPACE
          )
      AND NVL(TGT.LIFECYCLE_STATUS, '') <> 'Decommissioned';

    v_deleted_count := SQLROWCOUNT;

    -- -------------------------------------------------------------------------
    -- STEP 7: Capture run end timestamp
    -- -------------------------------------------------------------------------
    v_run_end_ts := CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ;

    -- -------------------------------------------------------------------------
    -- STEP 8: Log reconciliation record to ETL_RECONCILIATION_LOG
    -- -------------------------------------------------------------------------
    -- SECTION 5: Reconciliation
INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        DEDUP_COUNT,
        DELETED_COUNT,
        ERROR_MESSAGE,
        EXCLUDED_COUNT,
        INSERTED_COUNT,
        LAST_UPDATED_AT,
        LOAD_TYPE,
        PIPELINE_NAME,
        RUN_END_TS,
        RUN_START_TS,
        RUN_TIMESTAMP,