/*=========================================================
Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
WAREHOUSE = SNOWFLAKE_LEARNING_WH
AS
$$
-- SECTION 1: Variables

    -- Run metadata
    v_run_id            VARCHAR;
    v_run_timestamp     TIMESTAMP_NTZ;
    v_load_type         VARCHAR;
    v_current_watermark TIMESTAMP_NTZ;
    v_last_watermark    TIMESTAMP_NTZ;
    v_start_time        TIMESTAMP_NTZ;
    v_end_time          TIMESTAMP_NTZ;
    v_duration_seconds  NUMBER;

    -- Record counts
    v_source_count      NUMBER DEFAULT 0;
    v_target_count      NUMBER DEFAULT 0;
    v_insert_count      NUMBER DEFAULT 0;
    v_update_count      NUMBER DEFAULT 0;
    v_dedup_count       NUMBER DEFAULT 0;
    v_filtered_count    NUMBER DEFAULT 0;
    v_soft_delete_count NUMBER DEFAULT 0;

    -- Status / error
    v_status            VARCHAR DEFAULT 'SUCCESS';
    v_error_message     VARCHAR DEFAULT NULL;

    -- Result
    v_result            VARCHAR;

BEGIN
    -- ----------------------------------------------------------------
    -- 1. Initialise run metadata
    -- ----------------------------------------------------------------
    v_run_id        := GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SEQ_ETL_RUN_ID.NEXTVAL::VARCHAR;
    v_run_timestamp := CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ;
    v_start_time    := v_run_timestamp;

    -- ----------------------------------------------------------------
    -- 2. Determine last successful watermark
    -- ----------------------------------------------------------------
    -- SECTION 2: Source Processing
SELECT -- SECTION 3: Data Validation
COALESCE(MAX(CURRENT_WATERMARK), '1900-01-01 00:00:00'::TIMESTAMP_NTZ)
      INTO v_last_watermark
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
     WHERE STATUS = 'SUCCESS';

    -- ----------------------------------------------------------------
    -- 3. Determine load type
    -- ----------------------------------------------------------------
    IF (v_last_watermark = '1900-01-01 00:00:00'::TIMESTAMP_NTZ) THEN
        v_load_type := 'FULL';
    ELSE
        v_load_type := 'INCREMENTAL';
    END IF;

    -- ----------------------------------------------------------------
    -- 4. Stage deduplicated source records into a temporary table
    --    Keep the latest record per PART_NUMBER based on UPDATED_AT
    -- ----------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_PARTS_STAGE AS
    WITH ranked AS (
        SELECT
            PART_NUMBER,
            CERTIFICATION_STATUS,
            INSTALLATION_DATE,
            LEAD_TIME_DAYS,
            LIFECYCLE_STATUS,
            MANUFACTURER,
            UNIT_PRICE_USD,
            UPDATED_AT,
            WEIGHT_KG,
            ROW_NUMBER() OVER (
                PARTITION BY PART_NUMBER
                ORDER BY UPDATED_AT DESC
            ) AS rn
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE
            PART_NUMBER IS NOT NULL
            AND (
                v_load_type = 'FULL'
                OR UPDATED_AT > v_last_watermark
            )
    )
    SELECT
        PART_NUMBER,
        CERTIFICATION_STATUS,
        INSTALLATION_DATE,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        MANUFACTURER,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WEIGHT_KG
    FROM ranked
    WHERE rn = 1;

    -- ----------------------------------------------------------------
    -- 5. Capture counts
    -- ----------------------------------------------------------------

    -- Total raw source rows in scope (before dedup)
    SELECT COUNT(*)
      INTO v_source_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
     WHERE
         PART_NUMBER IS NOT NULL
         AND (
             v_load_type = 'FULL'
             OR UPDATED_AT > v_last_watermark
         );

    -- Deduplicated staged rows
    SELECT COUNT(*)
      INTO v_dedup_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_PARTS_STAGE;

    -- Rows filtered out due to NULL PART_NUMBER (excluded)
    v_filtered_count := v_source_count - v_dedup_count;

    -- Current target row count (before merge)
    SELECT COUNT(*)
      INTO v_target_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;

    -- ----------------------------------------------------------------
    -- 6. SCD Type 1 -- SECTION 4: Merge Logic
MERGE into AEROSPACE_PARTS_TARGET
    --    Business key : PART_NUMBER
    --    Derived col  : RISK_SCORE
    --    RISK_SCORE logic:
    --      HIGH   -> 3  (LIFECYCLE_STATUS = 'END_OF_LIFE' or CERTIFICATION_STATUS = 'EXPIRED')
    --      MEDIUM -> 2  (LEAD_TIME_DAYS > 90)
    --      LOW    -> 1  (all other cases)
    -- ----------------------------------------------------------------
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET  AS tgt
    USING GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_PARTS_STAGE    AS src
       ON tgt.PART_NUMBER = src.PART_NUMBER

    -- ---- MATCHED: update changed rows (SCD1 overwrite) ----
    WHEN MATCHED
         AND (
               ZEROIFNULL(tgt.UNIT_PRICE_USD)       <> ZEROIFNULL(src.UNIT_PRICE_USD)
            OR ZEROIFNULL(tgt.WEIGHT_KG)             <> ZEROIFNULL(src.WEIGHT_KG)
            OR ZEROIFNULL(tgt.LEAD_TIME_DAYS)        <> ZEROIFNULL(src.LEAD_TIME_DAYS)
            OR COALESCE(tgt.CERTIFICATION_STATUS,'') <> COALESCE(src.CERTIFICATION_STATUS,'')
            OR COALESCE(tgt.LIFECYCLE_STATUS,'')     <> COALESCE(src.LIFECYCLE_STATUS,'')
            OR COALESCE(tgt.MANUFACTURER,'')         <> COALESCE(src.MANUFACTURER,'')
            OR COALESCE(tgt.INSTALLATION_DATE::VARCHAR,'') <> COALESCE(src.INSTALLATION_DATE::VARCHAR,'')
            OR COALESCE(tgt.UPDATED_AT::VARCHAR,'')  <> COALESCE(src.UPDATED_AT::VARCHAR,'')
         )
    THEN UPDATE SET
        tgt.CERTIFICATION_STATUS  = src.CERTIFICATION_STATUS,
        tgt.INSTALLATION_DATE     = src.INSTALLATION_DATE,
        tgt.LEAD_TIME_DAYS        = src.LEAD_TIME_DAYS,
        tgt.LIFECYCLE_STATUS      = src.LIFECYCLE_STATUS,
        tgt.MANUFACTURER          = src.MANUFACTURER,
        tgt.UNIT_PRICE_USD        = src.UNIT_PRICE_USD,
        tgt.UPDATED_AT            = src.UPDATED_AT,
        tgt.WEIGHT_KG             = src.WEIGHT_KG,
        tgt.RECORD_STATUS         = 'ACTIVE',
        tgt.RISK_SCORE            = CASE
                                        WHEN src.LIFECYCLE_STATUS    = 'END_OF_LIFE'
                                          OR src.CERTIFICATION_STATUS = 'EXPIRED'  THEN 3
                                        WHEN src.LEAD_TIME_DAYS > 90               THEN 2
                                        ELSE 1
                                    END,
        tgt.DW_UPDATE_TIMESTAMP   = v_run_timestamp

    -- ---- NOT MATCHED: insert new rows ----
    WHEN NOT MATCHED THEN
    INSERT (
        PART_NUMBER,
        CERTIFICATION_STATUS,
        INSTALLATION_DATE,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        MANUFACTURER,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WEIGHT_KG,
        RECORD_STATUS,
        RISK_SCORE,
        DW_INSERT_TIMESTAMP,
        DW_UPDATE_TIMESTAMP
    )
    VALUES (
        src.PART_NUMBER,
        src.CERTIFICATION_STATUS,
        src.INSTALLATION_DATE,
        src.LEAD_TIME_DAYS,
        src.LIFECYCLE_STATUS,
        src.MANUFACTURER,
        src.UNIT_PRICE_USD,
        src.UPDATED_AT,
        src.WEIGHT_KG,
        'ACTIVE',
        CASE
            WHEN src.LIFECYCLE_STATUS    = 'END_OF_LIFE'
              OR src.CERTIFICATION_STATUS = 'EXPIRED'  THEN 3
            WHEN src.LEAD_TIME_DAYS > 90               THEN 2
            ELSE 1
        END,
        v_run_timestamp,
        v_run_timestamp
    );

    -- ----------------------------------------------------------------
    -- 7. Capture INSERT / UPDATE counts from MERGE
    -- ----------------------------------------------------------------
    -- Rows inserted = target rows that did not exist before the merge
    SELECT COUNT(*)
      INTO v_insert_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET tgt
     WHERE tgt.DW_INSERT_TIMESTAMP = v_run_timestamp
       AND tgt.DW_UPDATE_TIMESTAMP = v_run_timestamp;

    -- Rows updated = rows touched by merge but not newly inserted
    SELECT COUNT(*)
      INTO v_update_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET tgt
     WHERE tgt.DW_UPDATE_TIMESTAMP = v_run_timestamp
       AND tgt.DW_INSERT_TIMESTAMP <> v_run_timestamp;

    -- ----------------------------------------------------------------
    -- 8. Soft-delete: mark ACTIVE target rows absent from source
    --    as INACTIVE (only on FULL load or when explicitly required)
    -- ----------------------------------------------------------------
    IF (v_load_type = 'FULL') THEN
        UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET tgt
           SET tgt.RECORD_STATUS       = 'INACTIVE',
               tgt.DW_UPDATE_TIMESTAMP = v_run_timestamp
         WHERE tgt.RECORD_STATUS = 'ACTIVE'
           AND NOT EXISTS (
               SELECT 1
                 FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_PARTS_STAGE src
                WHERE src.PART_NUMBER = tgt.PART_NUMBER
           );

        SELECT COUNT(*)
          INTO v_soft_delete_count
          FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
         WHERE RECORD_STATUS       = 'INACTIVE'
           AND DW_UPDATE_TIMESTAMP = v_run_timestamp;
    END IF;

    -- ----------------------------------------------------------------
    -- 9. Determine current watermark (max UPDATED_AT processed)
    -- ----------------------------------------------------------------
    SELECT COALESCE(MAX(UPDATED_AT), v_last_watermark)
      INTO v_current_watermark
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_PARTS_STAGE;

    -- ----------------------------------------------------------------
    -- 10. Calculate duration
    -- ----------------------------------------------------------------
    v_end_time         := CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ;
    v_duration_seconds := DATEDIFF('second', v_start_time, v_end_time);

    -- ----------------------------------------------------------------
    -- 11. Write reconciliation log — SUCCESS
    -- ----------------------------------------------------------------
    -- SECTION 5: Reconciliation
INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        RUN_ID,
        RUN_TIMESTAMP,
        LOAD_TYPE,
        SOURCE_COUNT,
        TARGET_COUNT,
        INSERT_COUNT,
        UPDATE_COUNT,
        DEDUP_COUNT,
        FILTERED_COUNT,
        SOFT_DELETE_COUNT,
        CURRENT_WATERMARK,
        LAST_RUN_TIMESTAMP,
        DURATION_SECONDS,
        STATUS,
        ERROR_MESSAGE
    )
    VALUES (
        v_run_id,
        v_run_timestamp,
        v_load_type,
        v_source_count,
        v_target_count,
        v_insert_count,
        v_update_count,
        v_dedup_count,
        v_filtered_count,
        v_soft_delete_count,
        v_current_watermark,
        v_last_watermark,
        v_duration_seconds,
        v_status,
        v_error_message
    );

    -- ----------------------------------------------------------------
    -- 12. Return success summary
    -- ----------------------------------------------------------------
    v_result := OBJECT_CONSTRUCT(
        'status',            v_status,
        'run_id',            v_run_id,
        'load_type',         v_load_type,
        'source_count',      v_source_count,
        'insert_count',      v_insert_count,
        'update_count',      v_update_count,
        'dedup_count',       v_dedup_count,
        'filtered_count',    v_filtered_count,
        'soft_delete_count', v_soft_delete_count,
        'current_watermark', v_current_watermark::VARCHAR,
        'duration_seconds',  v_duration_seconds
    )::VARCHAR;

    RETURN v_result;

-- SECTION 6: Error Handling
EXCEPTION
    WHEN OTHER THEN
        -- ----------------------------------------------------------------
        -- 13. Capture error details and write FAILED reconciliation log
        -- ----------------------------------------------------------------
        v_status        := 'FAILED';
        v_error_message := SQLERRM;
        v_end_time      := CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ;
        v_duration_seconds := DATEDIFF('second', v_start_time, v_end_time);

        INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
            RUN_ID,
            RUN_TIMESTAMP,
            LOAD_TYPE,
            SOURCE_COUNT,
            TARGET_COUNT,
            INSERT_COUNT,
            UPDATE_COUNT,
            DEDUP_COUNT,
            FILTERED_COUNT,
            SOFT_DELETE_COUNT,
            CURRENT_WATERMARK,
            LAST_RUN_TIMESTAMP,
            DURATION_SECONDS,
            STATUS,
            ERROR_MESSAGE
        )
        VALUES (
            v_run_id,
            v_run_timestamp,
            v_load_type,
            v_source_count,
            v_target_count,
            v_insert_count,
            v_update_count,
            v_dedup_count,
            v_filtered_count,
            v_soft_delete_count,
            v_current_watermark,
            v_last_watermark,
            v_duration_seconds,
            v_status,
            v_error_message
        );