/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_TARGET
Purpose     : SCD Type 1 analytics-ready target table for aerospace parts inventory
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET (
    PART_NUMBER         VARCHAR(100)    NOT NULL,
    MANUFACTURER        VARCHAR(255),
    WEIGHT_KG           NUMBER(10,3),
    UNIT_PRICE_USD      NUMBER(15,2),
    LIFECYCLE_STATUS    VARCHAR(100),
    INSTALLATION_DATE   DATE,
    CERTIFICATION       VARCHAR(100),
    LEAD_TIME_DAYS      NUMBER(6),
    RISK_SCORE          VARCHAR(20),
    IS_DELETED          BOOLEAN         DEFAULT FALSE,
    UPDATED_AT          TIMESTAMP_NTZ,
    CREATED_AT          TIMESTAMP_NTZ,
    DW_INSERTED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT       TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

-- SECTION 2: Constraints
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    ADD CONSTRAINT PK_APT_PART_NUMBER PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- SCD Type 1: updates overwrite existing records; no history retained.
-- RISK_SCORE derived: High/Medium/Low based on CERTIFICATION and LEAD_TIME_DAYS.
-- IS_DELETED = TRUE indicates soft-deleted (Decommissioned) records.
-- DW_UPDATED_AT refreshed on every merge update.