/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_SOURCE
Purpose     : Source/staging table for aerospace parts inventory raw ingestion
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE (
    PART_NUMBER          VARCHAR(100)     NOT NULL,
    MANUFACTURER         VARCHAR(255),
    WEIGHT_KG            NUMBER(10,4),
    UNIT_PRICE_USD       NUMBER(14,4),
    LIFECYCLE_STATUS     VARCHAR(100),
    INSTALLATION_DATE    DATE,
    CERTIFICATION_STATUS VARCHAR(100),
    LEAD_TIME_DAYS       NUMBER(6,0),
    UPDATED_AT           TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    ADD CONSTRAINT PK_AEROSPACE_PARTS_SOURCE PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- Raw ingestion table; no transformations applied at this layer.
-- UPDATED_AT drives incremental load watermark in the ETL stored procedure.