/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_TARGET
Purpose     : SCD Type 1 analytics-ready target table for aerospace parts inventory
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET (
    PART_NUMBER             VARCHAR(100)     NOT NULL,
    MANUFACTURER            VARCHAR(255),
    WEIGHT_KG               NUMBER(10,4),
    UNIT_PRICE_USD          NUMBER(14,2),
    LIFECYCLE_STATUS        VARCHAR(100),
    INSTALLATION_DATE       DATE,
    CERTIFICATION_STATUS    VARCHAR(100),
    LEAD_TIME_DAYS          NUMBER(6,0),
    UPDATED_AT              TIMESTAMP_NTZ,
    RISK_SCORE              VARCHAR(20),
    ETL_LOAD_TIMESTAMP      TIMESTAMP_NTZ,
    DECOMMISSION_TIMESTAMP  TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    ADD CONSTRAINT PK_AEROSPACE_PARTS_TARGET PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- SCD Type 1: updates overwrite existing records; no history retained.
-- RISK_SCORE derived from CERTIFICATION_STATUS + LEAD_TIME_DAYS logic in SP.
-- DECOMMISSION_TIMESTAMP populated on soft delete; LIFECYCLE_STATUS set to Decommissioned.