/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : Pipeline audit and reconciliation log for each ETL run
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
    RUN_ID                VARCHAR(100)     NOT NULL,
    RUN_TIMESTAMP         TIMESTAMP_NTZ,
    SOURCE_COUNT          NUMBER(12,0),
    TARGET_COUNT_BEFORE   NUMBER(12,0),
    TARGET_COUNT_AFTER    NUMBER(12,0),
    INSERT_COUNT          NUMBER(12,0),
    UPDATE_COUNT          NUMBER(12,0),
    SOFT_DELETE_COUNT     NUMBER(12,0),
    RUN_STATUS            VARCHAR(50),
    LAST_UPDATED_AT       TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    ADD CONSTRAINT PK_ETL_RECONCILIATION_LOG PRIMARY KEY (RUN_ID);

-- SECTION 3: Notes
-- RUN_ID generated as UUID per execution via UUID_STRING().
-- LAST_UPDATED_AT captures the max UPDATED_AT watermark from source for next incremental run.
-- RUN_STATUS values: SUCCESS | FAILED.