/*=========================================================
Object Name : QA_AEROSPACE_PARTS_PIPELINE
Purpose     : QA acceptance criteria queries AC-001 to AC-010
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

-- FILE        : QA_AEROSPACE_PARTS_PIPELINE.sql
-- DATABASE    : GEN_AI_POC_SNOWFLAKECOE
-- SCHEMA      : SDLC_WIZARD
-- WAREHOUSE   : SNOWFLAKE_LEARNING_WH
-- PASS CRITERIA: All queries return PASS or zero violation rows.

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;

-- AC-002
USE SCHEMA SDLC_WIZARD;

-- AC-003
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- ── AC-001: Row Count Reconciliation ─────────────────────
-- PASS: TARGET_COUNT_AFTER >= SOURCE_COUNT (after exclusions)
-- PASS: No run logged with NULL counts
SELECT
    'AC-001' AS CRITERIA,
    RUN_ID,
    SOURCE_COUNT,
    TARGET_COUNT_BEFORE,
    TARGET_COUNT_AFTER,
    INSERT_COUNT,
    UPDATE_COUNT,
    SOFT_DELETE_COUNT,
    CASE
        WHEN TARGET_COUNT_AFTER IS NULL OR SOURCE_COUNT IS NULL THEN 'FAIL - NULL counts'
        WHEN TARGET_COUNT_AFTER < TARGET_COUNT_BEFORE AND SOFT_DELETE_COUNT = 0 THEN 'FAIL - unexpected row drop'
        ELSE 'PASS'
    END AS STATUS
FROM ETL_RECONCILIATION_LOG
ORDER BY RUN_TIMESTAMP DESC
LIMIT 1;

-- ── AC-002: RISK_SCORE Distribution ──────────────────────
-- PASS: Only valid values exist; no NULLs
SELECT
    'AC-002'                                        AS CRITERIA,
    RISK_SCORE,
    COUNT(*)                                        AS PART_COUNT,
    CASE
        WHEN RISK_SCORE NOT IN ('High Risk','Medium Risk','Low Risk') THEN 'FAIL - invalid value'
        ELSE 'PASS'
    END                                             AS STATUS
FROM AEROSPACE_PARTS_TARGET
GROUP BY RISK_SCORE
UNION ALL
SELECT 'AC-002', 'NULL_CHECK', COUNT(*), 'FAIL - NULL RISK_SCORE'
FROM AEROSPACE_PARTS_TARGET
WHERE RISK_SCORE IS NULL
HAVING COUNT(*) > 0;

-- ── AC-003: NULL WEIGHT_KG Validation ────────────────────
-- PASS: All WEIGHT_KG <= 0 from source are stored as NULL in target
SELECT
    'AC-003'  AS CRITERIA,
    COUNT(*)  AS VIOLATIONS,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL - non-positive WEIGHT_KG not nulled' END AS STATUS
FROM AEROSPACE_PARTS_TARGET
WHERE WEIGHT_KG <= 0;

-- ── AC-004: UNIT_PRICE_USD Rounding ──────────────────────
-- PASS: No value has more than 2 decimal places
SELECT
    'AC-004'  AS CRITERIA,
    COUNT(*)  AS VIOLATIONS,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL - UNIT_PRICE_USD not rounded to 2dp' END AS STATUS
FROM AEROSPACE_PARTS_TARGET
WHERE UNIT_PRICE_USD <> ROUND(UNIT_PRICE_USD, 2);

-- ── AC-005: MANUFACTURER CamelCase Validation ────────────
-- PASS: MANUFACTURER matches INITCAP transformation (no all-upper or all-lower)
SELECT
    'AC-005'  AS CRITERIA,
    COUNT(*)  AS VIOLATIONS,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL - MANUFACTURER not CamelCase' END AS STATUS
FROM AEROSPACE_PARTS_TARGET
WHERE MANUFACTURER IS NOT NULL
  AND MANUFACTURER <> INITCAP(MANUFACTURER);

-- ──