/*=========================================================
Object Name : SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

-- ============================================================
-- FILE        : SP_LOAD_AEROSPACE_PARTS_SCD1.sql
-- DATABASE    : GEN_AI_POC_SNOWFLAKECOE
-- SCHEMA      : SDLC_WIZARD
-- WAREHOUSE   : SNOWFLAKE_LEARNING_WH
-- OBJECT      : SP_LOAD_AEROSPACE_PARTS_SCD1 (STORED PROCEDURE)
-- PURPOSE     : Incremental SCD Type 1 load with full rules
-- ============================================================

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
    var pipeline   = 'SP_LOAD_AEROSPACE_PARTS_SCD1';
    var run_start  = new Date().toISOString();
    var status     = 'SUCCESS';
    var err_msg    = '';
    var src_cnt=0, dedup_cnt=0, excl_cnt=0, ins_cnt=0, upd_cnt=0, soft_cnt=0, tgt_cnt=0;
    var wm_-- SECTION 2: Source Processing
from    = '1900-01-01 00:00:00';
    var wm_to      = '';

    try {
        // STEP 1: Get watermark
        var wm_sql = `SELECT -- SECTION 3: Data Validation
COALESCE(MAX(WATERMARK_TO), '1900-01-01 00:00:00'::TIMESTAMP_NTZ)
                      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
                      WHERE PIPELINE_NAME = '${pipeline}' AND STATUS = 'SUCCESS'`;
        var wm_res = snowflake.execute({sqlText: wm_sql});
        wm_res.next();
        wm_from = wm_res.getColumnValue(1);

        var wm_to_sql = `SELECT MAX(UPDATED_AT) FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE`;
        var wm_to_res = snowflake.execute({sqlText: wm_to_sql});
        wm_to_res.next();
        wm_to = wm_to_res.getColumnValue(1);

        // STEP 2: Source count
        var sc = snowflake.execute({sqlText:
            `SELECT COUNT(*) FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
             WHERE UPDATED_AT > '${wm_from}'::TIMESTAMP_NTZ`});
        sc.next(); src_cnt = sc.getColumnValue(1);

        // STEP 3: Build deduplicated + transformed staging CTE and merge
        var merge_sql = `
-- SECTION 4: Merge Logic
MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET T
USING (
    WITH DEDUPED AS (
        SELECT *,
               ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE UPDATED_AT > '${wm_from}'::TIMESTAMP_NTZ
          AND NOT (CATEGORY = 'Obsolete' AND STOCK_QUANTITY = 0)
    ),
    TRANSFORMED AS (
        SELECT
            PART_NUMBER,
            PART_NAME,
            INITCAP(MANUFACTURER)                                          AS MANUFACTURER,
            CATEGORY,
            CASE WHEN WEIGHT_KG <= 0 THEN NULL ELSE WEIGHT_KG END         AS WEIGHT_KG,
            ROUND(UNIT_PRICE_USD, 2)                                       AS UNIT_PRICE_USD,
            CERTIFICATION_STATUS,
            LEAD_TIME_DAYS,
            STOCK_QUANTITY,
            WAREHOUSE_LOCATION,
            SUPPLIER_ID,
            LAST_INSPECTION_DATE,
            UPDATED_AT,
            CREATED_AT,
            CASE
                WHEN (WEIGHT_KG <= 0 OR WEIGHT_KG IS NULL)
                     AND DATEDIFF('day', LAST_INSPECTION_DATE, CURRENT_DATE()) > 90
                     THEN 'High Risk'
                WHEN (CERTIFICATION_STATUS = 'Pending' OR LEAD_TIME_DAYS > 120)
                     THEN 'Medium Risk'
                WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual')
                     AND LEAD_TIME_DAYS <= 60
                     THEN 'Low Risk'
                ELSE 'Medium Risk'
            END AS RISK_SCORE
        FROM DEDUPED
        WHERE RN = 1
    )
    SELECT * FROM TRANSFORMED
) S
ON T.PART_NUMBER = S.PART_NUMBER
WHEN MATCHED THEN UPDATE SET
    T.PART_NAME              = S.PART_NAME,
    T.MANUFACTURER           = S.MANUFACTURER,
    T.CATEGORY               = S.CATEGORY,
    T.WEIGHT_KG              = S.WEIGHT_KG,
    T.UNIT_PRICE_USD         = S.UNIT_PRICE_USD,
    T.CERTIFICATION_STATUS   = S.CERTIFICATION_STATUS,
    T.LEAD_TIME_DAYS         = S.LEAD_TIME_DAYS,
    T.STOCK_QUANTITY         = S.STOCK_QUANTITY,
    T.WAREHOUSE_LOCATION     = S.WAREHOUSE_LOCATION,
    T.SUPPLIER_ID            = S.SUPPLIER_ID,
    T.LAST_INSPECTION_DATE   = S.LAST_INSPECTION_DATE,
    T.UPDATED_AT             = S.UPDATED_AT,
    T.RISK_SCORE             = S.RISK_SCORE,
    T.RECORD_STATUS          = 'Active',
    T.PIPELINE_LOAD_TIMESTAMP= CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    PART_NUMBER, PART_NAME, MANUFACTURER, CATEGORY, WEIGHT_KG, UNIT_PRICE_USD,
    CERTIFICATION_STATUS, LEAD_TIME_DAYS, STOCK_QUANTITY, WAREHOUSE_LOCATION,
    SUPPLIER_ID, LAST_INSPECTION_DATE, UPDATED_AT, CREATED_AT,
    RISK_SCORE, RECORD_STATUS, PIPELINE_LOAD_TIMESTAMP
) VALUES (
    S.PART_NUMBER, S.PART_NAME, S.MANUFACTURER, S.CATEGORY, S.WEIGHT_KG, S.UNIT_PRICE_USD,
    S.CERTIFICATION_STATUS, S.LEAD_TIME_DAYS, S.STOCK_QUANTITY, S.WAREHOUSE_LOCATION,
    S.SUPPLIER_ID, S.LAST_INSPECTION_DATE, S.UPDATED_AT, S.CREATED_AT,
    S.RISK_SCORE, 'Active', CURRENT_TIMESTAMP()
)`;
        var merge_res = snowflake.execute({sqlText: merge_sql});
        merge_res.next();
        upd_cnt = merge_res.getColumnValue(1);
        ins_cnt = merge_res.getColumnValue(2);

        // STEP 4: Dedup count
        var dc = snowflake.execute({sqlText:
            `SELECT COUNT(DISTINCT PART_NUMBER) FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
             WHERE UPDATED_AT > '${wm_from}'::TIMESTAMP_NTZ`});
        dc.next(); dedup_cnt = dc.getColumnValue(1);

        // STEP 5: Excluded count
        var ec = snowflake.execute({sqlText:
            `SELECT COUNT(*) FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
             WHERE UPDATED_AT > '${wm_from}'::TIMESTAMP_NTZ
               AND CATEGORY = 'Obsolete' AND STOCK_QUANTITY = 0`});
        ec.next(); excl_cnt = ec.getColumnValue(1);

        // STEP 6: Soft delete
        var soft_sql = `
UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET T
SET T.RECORD_STATUS = 'Decommissioned',
    T.PIPELINE_LOAD_TIMESTAMP = CURRENT_TIMESTAMP()
WHERE T.RECORD_STATUS = 'Active'
  AND NOT EXISTS (
      SELECT 1 FROM GEN_AI_POC_SNOWFLAKECOE.SD