/*=========================================================
Object Name : SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : SCD Type 1 pipeline for Aerospace Parts Inventory
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    -- SECTION 1: Variables
    v_batch_id          VARCHAR;
    v_start_ts          TIMESTAMP_NTZ;
    v_end_ts            TIMESTAMP_NTZ;
    v_src_count         INTEGER;
    v_insert_count      INTEGER;
    v_update_count      INTEGER;
    v_delete_count      INTEGER;
    v_reject_count      INTEGER;
    v_last_load_ts      TIMESTAMP_NTZ;
    v_tgt_count_before  INTEGER;
    v_tgt_count_after   INTEGER;
    v_result            VARCHAR;

BEGIN
    -- SECTION 2: Source Processing
    v_batch_id := UUID_STRING();
    v_start_ts := CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COALESCE(MAX(RUN_TIMESTAMP), '1900-01-01'::TIMESTAMP_NTZ)
      INTO v_last_load_ts
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
     WHERE PROCEDURE_NAME = 'SP_LOAD_AEROSPACE_PARTS_SCD1'
       AND RUN_STATUS = 'SUCCESS';

    -- Stage deduplicated incremental source with transformations
    CREATE OR REPLACE TEMPORARY TABLE TEMP_AEROSPACE_STAGE AS
    WITH DEDUP AS (
        SELECT *,
               ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN
          FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
         WHERE UPDATED_AT > v_last_load_ts
    )
    SELECT
        PART_NUMBER,
        INITCAP(MANUFACTURER)                                          AS MANUFACTURER,
        NULLIF(CASE WHEN WEIGHT_KG <= 0 THEN NULL ELSE WEIGHT_KG END, 0) AS WEIGHT_KG,
        ROUND(UNIT_PRICE_USD, 2)                                       AS UNIT_PRICE_USD,
        LIFECYCLE_STATUS,
        INSTALLATION_DATE,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,
        UPDATED_AT,
        CASE
            WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 90  THEN 'High Risk'
            WHEN CERTIFICATION_STATUS = 'Pending' OR  LEAD_TIME_DAYS > 120 THEN 'Medium Risk'
            WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 60 THEN 'Low Risk'
            ELSE 'Medium Risk'
        END                                                            AS RISK_SCORE
      FROM DEDUP
     WHERE RN = 1
       AND NOT (LIFECYCLE_STATUS = 'End of Life'
                AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE()));

    -- SECTION 3: Data Validation
    SELECT COUNT(*) INTO v_src_count        FROM TEMP_AEROSPACE_STAGE;
    SELECT COUNT(*) INTO v_tgt_count_before FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;
    SELECT COUNT(*) INTO v_reject_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
     WHERE UPDATED_AT > v_last_load_ts
       AND LIFECYCLE_STATUS = 'End of Life'
       AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE());

    -- SECTION 4: Merge Logic
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET  T
    USING TEMP_AEROSPACE_STAGE                                               S
       ON T.PART_NUMBER = S.PART_NUMBER
    WHEN MATCHED THEN UPDATE SET
        T.MANUFACTURER          = S.MANUFACTURER,
        T.WEIGHT_KG             = S.WEIGHT_KG,
        T.UNIT_PRICE_USD        = S.UNIT_PRICE_USD,
        T.LIFECYCLE_STATUS      = S.LIFECYCLE_STATUS,
        T.INSTALLATION_DATE     = S.INSTALLATION_DATE,
        T.CERTIFICATION_STATUS  = S.CERTIFICATION_STATUS,
        T.LEAD_TIME_DAYS        = S.LEAD_TIME_DAYS,
        T.UPDATED_AT            = S.UPDATED_AT,
        T.RISK_SCORE            = S.RISK_SCORE,
        T.ETL_LOAD_TIMESTAMP    = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER, MANUFACTURER, WEIGHT_KG, UNIT_PRICE_USD,
        LIFECYCLE_STATUS, INSTALLATION_DATE, CERTIFICATION_STATUS,
        LEAD_TIME_DAYS, UPDATED_AT, RISK_SCORE, ETL_LOAD_TIMESTAMP, DECOMMISSION_TIMESTAMP
    ) VALUES (
        S.PART_NUMBER, S.MANUFACTURER, S.WEIGHT_KG, S.UNIT_PRICE_USD,
        S.LIFECYCLE_STATUS, S.INSTALLATION_DATE, S.CERTIFICATION_STATUS,
        S.LEAD_TIME_DAYS, S.UPDATED_AT, S.RISK_SCORE,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ, NULL
    );

    SELECT COUNT(*) INTO v_insert_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
     WHERE ETL_LOAD_TIMESTAMP >= v_start_ts AND DECOMMISSION_TIMESTAMP IS NULL;

    -- Soft-delete parts absent from source (not in staging and not already decommissioned)
    UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET T
       SET T.LIFECYCLE_STATUS       = 'Decommissioned',
           T.DECOMMISSION_TIMESTAMP = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
           T.ETL_LOAD_TIMESTAMP     = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
     WHERE T.LIFECYCLE_STATUS <> 'Decommissioned'
       AND NOT EXISTS (
           SELECT 1 FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE S
            WHERE S.PART_NUMBER = T.PART_NUMBER
       );

    SELECT COUNT(*) INTO v_delete_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
     WHERE DECOMMISSION_TIMESTAMP >= v_start_ts;

    v_update_count := v_insert_count - v_delete_count;
    SELECT COUNT(*) INTO v_tgt_count_after FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;
    v_end_ts := CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- SECTION 5: Reconciliation
    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        RUN_ID, RUN_TIMESTAMP, PROCEDURE_NAME, SOURCE_COUNT,
        TARGET_COUNT_BEFORE, TARGET_COUNT_AFTER,
        INSERT_COUNT, UPDATE_COUNT, SOFT_DELETE_COUNT,
        REJECT_COUNT, RUN_STATUS, LAST_UPDATED_AT
    ) VALUES (
        v_batch_id, v_start_ts, 'SP_LOAD_AEROSPACE_PARTS_SCD1', v_src_count,
        v_tgt_count_before, v_tgt_count_after,
        v_insert_count, v_update_count, v_delete_count,
        v_reject_count, 'SUCCESS', v_end_ts
    );

    -- SECTION 6: Error Handling
    v_result := OBJECT_CONSTRUCT(
        'status',        'SUCCESS',
        'batch_id',      v_batch_id,
        'src_count',     v_src_count,
        'insert_count',  v_insert_count,
        'update_count',  v_update_count,
        'delete_count',  v_delete_count,
        'reject_count',  v_reject_count
    )::VARCHAR;
    RETURN v_result;

EXCEPTION WHEN OTHER THEN
    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        RUN_ID, RUN_TIMESTAMP, PROCEDURE_NAME, SOURCE_COUNT,
        TARGET_COUNT_BEFORE, TARGET_COUNT_AFTER,
        INSERT_COUNT, UPDATE_COUNT, SOFT_DELETE_COUNT,
        REJECT_COUNT, RUN_STATUS, LAST_UPDATED_AT
    ) VALUES (
        v_batch_id, v_start_ts, 'SP_LOAD_AEROSPACE_PARTS_SCD1', v_src_count,
        v_tgt_count_before, 0, 0, 0, 0, 0, 'FAILED',
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
    );
    RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;