/*=========================================================
Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Daily CRON task calling SP_LOAD_AEROSPACE_PARTS_SCD1
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- ── DDL: SOURCE ──────────────────────────────────────────
CREATE OR REPLACE TABLE AEROSPACE_PARTS_SOURCE (
    PART_NUMBER          VARCHAR(100)     NOT NULL PRIMARY KEY,
    MANUFACTURER         VARCHAR(200),
    WEIGHT_KG            NUMBER(10,4),
    UNIT_PRICE_USD       NUMBER(14,4),
    LIFECYCLE_STATUS     VARCHAR(100),
    INSTALLATION_DATE    DATE,
    CERTIFICATION_STATUS VARCHAR(100),
    LEAD_TIME_DAYS       NUMBER(6),
    UPDATED_AT           TIMESTAMP_NTZ
);

-- ── DDL: TARGET ──────────────────────────────────────────
CREATE OR REPLACE TABLE AEROSPACE_PARTS_TARGET (
    PART_NUMBER            VARCHAR(100)  NOT NULL PRIMARY KEY,
    MANUFACTURER           VARCHAR(200),
    WEIGHT_KG              NUMBER(10,4),
    UNIT_PRICE_USD         NUMBER(14,2),
    LIFECYCLE_STATUS       VARCHAR(100),
    INSTALLATION_DATE      DATE,
    CERTIFICATION_STATUS   VARCHAR(100),
    LEAD_TIME_DAYS         NUMBER(6),
    UPDATED_AT             TIMESTAMP_NTZ,
    RISK_SCORE             VARCHAR(20),
    ETL_LOAD_TIMESTAMP     TIMESTAMP_NTZ,
    DECOMMISSION_TIMESTAMP TIMESTAMP_NTZ
);

-- ── DDL: RECONCILIATION LOG ───────────────────────────────
CREATE OR REPLACE TABLE ETL_RECONCILIATION_LOG (
    RUN_ID              VARCHAR(100),
    RUN_TIMESTAMP       TIMESTAMP_NTZ,
    SOURCE_COUNT        NUMBER,
    TARGET_COUNT_BEFORE NUMBER,
    TARGET_COUNT_AFTER  NUMBER,
    INSERT_COUNT        NUMBER,
    UPDATE_COUNT        NUMBER,
    SOFT_DELETE_COUNT   NUMBER,
    RUN_STATUS          VARCHAR(50),
    LAST_UPDATED_AT     TIMESTAMP_NTZ
);

-- ── STORED PROCEDURE ─────────────────────────────────────
CREATE OR REPLACE PROCEDURE SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
-- SECTION 1: Variables

    v_run_id              VARCHAR;
    v_run_ts              TIMESTAMP_NTZ;
    v_last_run_ts         TIMESTAMP_NTZ;
    v_source_count        NUMBER DEFAULT 0;
    v_target_before       NUMBER DEFAULT 0;
    v_target_after        NUMBER DEFAULT 0;
    v_insert_count        NUMBER DEFAULT 0;
    v_update_count        NUMBER DEFAULT 0;
    v_soft_delete_count   NUMBER DEFAULT 0;
    v_status              VARCHAR DEFAULT 'SUCCESS';
BEGIN
    v_run_id := 'RUN_' || TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDD_HH24MISS');
    v_run_ts := CURRENT_TIMESTAMP::TIMESTAMP_NTZ;

    -- Last successful run timestamp
    -- SECTION 2: Source Processing
SELECT -- SECTION 3: Data Validation
COALESCE(MAX(RUN_TIMESTAMP), '1900-01-01'::TIMESTAMP_NTZ)
      INTO v_last_run_ts
      FROM ETL_RECONCILIATION_LOG
     WHERE RUN_STATUS = 'SUCCESS';

    -- Target count before
    SELECT COUNT(*) INTO v_target_before FROM AEROSPACE_PARTS_TARGET;

    -- Stage: incremental + deduplicated + transformed + filtered
    CREATE OR REPLACE TEMPORARY TABLE STAGE_AEROSPACE_PARTS AS
    WITH INCREMENTAL AS (
        SELECT *
          FROM AEROSPACE_PARTS_SOURCE
         WHERE UPDATED_AT > :v_last_run_ts
    ),
    DEDUPED AS (
        SELECT *
          FROM (
            SELECT *,
                   ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN
              FROM INCREMENTAL
          )
         WHERE RN = 1
    ),
    TRANSFORMED AS (
        SELECT
            PART_NUMBER,
            INITCAP(MANUFACTURER)                                        AS MANUFACTURER,
            CASE WHEN WEIGHT_KG <= 0 THEN NULL ELSE WEIGHT_KG END        AS WEIGHT_KG,
            ROUND(UNIT_PRICE_USD, 2)                                     AS UNIT_PRICE_USD,
            LIFECYCLE_STATUS,
            INSTALLATION_DATE,
            CERTIFICATION_STATUS,
            LEAD_TIME_DAYS,
            UPDATED_AT
          FROM DEDUPED
    ),
    FILTERED AS (
        SELECT *
          FROM TRANSFORMED
         WHERE NOT (
               LIFECYCLE_STATUS = 'End of Life'
           AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE)
         )
    )
    SELECT
        PART_NUMBER,
        MANUFACTURER,
        WEIGHT_KG,
        UNIT_PRICE_USD,
        LIFECYCLE_STATUS,
        INSTALLATION_DATE,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,
        UPDATED_AT,
        CASE
            WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 90
                THEN 'High Risk'
            WHEN CERTIFICATION_STATUS = 'Pending' OR LEAD_TIME_DAYS > 120
                THEN 'Medium Risk'
            WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 60
                THEN 'Low Risk'
            ELSE 'Medium Risk'
        END AS RISK_SCORE
      FROM FILTERED;

    SELECT COUNT(*) INTO v_source_count FROM STAGE_AEROSPACE_PARTS;

    -- SCD1 MERGE
    -- SECTION 4: Merge Logic
MERGE INTO AEROSPACE_PARTS_TARGET T
    USING STAGE_AEROSPACE_PARTS S
       ON T.PART_NUMBER = S.PART_NUMBER
    WHEN MATCHED AND (
            T.MANUFACTURER        <> S.MANUFACTURER        OR
            NVL(T.WEIGHT_KG,-1)   <> NVL(S.WEIGHT_KG,-1)  OR
            T.UNIT_PRICE_USD      <> S.UNIT_PRICE_USD       OR
            T.LIFECYCLE_STATUS    <> S.LIFECYCLE_STATUS     OR
            T.INSTALLATION_DATE   <> S.INSTALLATION_DATE    OR
            T.CERTIFICATION_STATUS<> S.CERTIFICATION_STATUS OR
            T.LEAD_TIME_DAYS      <> S.LEAD_TIME_DAYS       OR
            T.RISK_SCORE          <> S.RISK_SCORE
        ) THEN UPDATE SET
            T.MANUFACTURER         = S.MANUFACTURER,
            T.WEIGHT_KG            = S.WEIGHT_KG,
            T.UNIT_PRICE_USD       = S.UNIT_PRICE_USD,
            T.LIFECYCLE_STATUS     = S.LIFECYCLE_STATUS,
            T.INSTALLATION_DATE    = S.INSTALLATION_DATE,
            T.CERTIFICATION_STATUS = S.CERTIFICATION_STATUS,
            T.LEAD_TIME_DAYS       = S.LEAD_TIME_DAYS,
            T.UPDATED_AT           = S.UPDATED_AT,
            T.RISK_SCORE           = S.RISK_SCORE,
            T.ETL_LOAD_TIMESTAMP   = :v_run_ts
    WHEN NOT MATCHED THEN INSERT (
            PART_NUMBER, MANUFACTURER, WEIGHT_KG, UNIT_PRICE_USD,
            LIFECYCLE_STATUS, INSTALLATION_DATE, CERTIFICATION_STATUS,
            LEAD_TIME_DAYS, UPDATED_AT, RISK_SCORE, ETL_LOAD_TIMESTAMP,
            DECOMMISSION_TIMESTAMP
        ) VALUES (
            S.PART_NUMBER, S.MANUFACTURER, S.WEIGHT_KG, S.UNIT_PRICE_USD,
            S.LIFECYCLE_STATUS, S.INSTALLATION_DATE, S.CERTIFICATION_STATUS,
            S.LEAD_TIME_DAYS, S.UPDATED_AT, S.RISK_SCORE, :v_run_ts, NULL
        );

    -- Capture insert/update counts via log delta (approximation via target diff)
    SELECT COUNT(*) INTO v_target_after FROM AEROSPACE_PARTS_TARGET;
    v_insert_count := v_target_after - v_target_before;
    v_update_count := v_source_count - v_insert_count;

    -- Soft delete: parts in target (active) not in source this run
    UPDATE AEROSPACE_PARTS_TARGET T
       SET T.LIFECYCLE_STATUS       = 'Decommissioned',
           T.DECOMMISSION_TIMESTAMP = :v_run_ts,
           T.ETL_LOAD_TIMESTAMP     = :v_run_ts
     WHERE T.LIFECYCLE_STATUS <> 'Decommissioned'
       AND NOT EXISTS (
           SELECT 1 FROM AEROSPACE_PARTS_SOURCE S
            WHERE S.PART_NUMBER = T.PART_NUMBER
       );

    v_soft_delete_count := SQLROWCOUNT;

    -- SECTION 5: Reconciliation
INSERT INTO ETL_RECONCILIATION_LOG
        (RUN_ID, RUN_TIMESTAMP, SOURCE_COUNT, TARGET_COUNT_BEFORE,
         TARGET_COUNT_AFTER, INSERT_COUNT, UPDATE_COUNT, SOFT_DELETE_COUNT,
         RUN_STATUS, LAST_UPDATED_AT)
    VALUES
        (:v_run_id, :v_run_ts, :v_source_count, :v_target_before,
         :v_target_after, :v_insert_count, :v_update_count, :v_soft_delete_count,
         :v_status, CURRENT_TIMESTAMP::TIMESTAMP_NTZ);

    RETURN 'SP_LOAD_AEROSPACE_PARTS_SCD1 completed. RUN_ID=' || v_run_id
        || ' INSERTS=' || v_insert_count
        || ' UPDATES=' || v_update_count
        || ' SOFT_DELETES=' || v_soft_delete_count;

-- SECTION 6: Error Handling
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO ETL_RECONCILIATION_LOG
            (RUN_ID, RUN_TIMESTAMP, SOURCE_COUNT, TARGET_COUNT_BEFORE,
             TARGET_COUNT_AFTER, INSERT_COUNT, UPDATE_COUNT, SOFT_DELETE_COUNT,
             RUN_STATUS, LAST_UPDATED_AT)
        VALUES
            (:v_run_id, :v_run_ts, :v_source_count, :v_target_before,
             0, 0, 0, 0, 'FAILED', CURRENT_TIMESTAMP::TIMESTAMP_NTZ);
        RETURN 'FAILED: ' || SQLERRM;

$$;

-- ── TASK ─────────────────────────────────────────────────
CREATE OR REPLACE TASK TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 2 * * * UTC'
AS
    CALL SP_LOAD_AEROSPACE_PARTS_SCD1();

ALTER TASK TASK_SP_LOAD_AEROSPACE_PARTS_SCD1 RESUME;