/*=========================================================
Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Daily scheduler at 02:00 UTC for SCD1 pipeline
Database    : GEN_AI_POC_SNOWFLAKECOE
Schema      : SDLC_WIZARD
Warehouse   : SNOWFLAKE_LEARNING_WH
=========================================================*/

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

CREATE OR REPLACE TASK SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
  WAREHOUSE = SNOWFLAKE_LEARNING_WH
  SCHEDULE  = 'USING CRON 0 2 * * * UTC'
  COMMENT   = 'Daily 02:00 UTC trigger for SP_LOAD_AEROSPACE_PARTS_SCD1'
AS
  CALL GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1();

-- Activate task
ALTER TASK SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1 RESUME;

-- Verify
SHOW TASKS LIKE 'TASK_SP_LOAD_AEROSPACE_PARTS_SCD1' IN SCHEMA SDLC_WIZARD;