/*==============================================================
Object Name    : 01_CREATE_TABLES
Purpose        : Create all base tables for customer and order
                 data pipeline in IDEA_2_DB.PUBLIC schema.
Generated By   : SDLC_DEVELOPER
Generated Date : 2025-01-24
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create base staging and target tables
---------------------------------------------------------

-- Create CUSTOMER table to hold customer master data
-- Purpose: Stores customer information loaded from CSV stage files
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMER (
    CUSTID          VARCHAR(50),
    NAME            VARCHAR(255),
    EMAILID         VARCHAR(255),
    REGION          VARCHAR(100)
);

-- Create ORDER table to hold order transactional data
-- Purpose: Stores order information loaded from CSV stage files including SCD2 tracking columns
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC."order" (
    ORDERID         VARCHAR(50),
    CUSTID          VARCHAR(50),
    ITEMNAME        VARCHAR(255),
    PRICEPERUNIT    NUMBER(18,2),
    QTY             NUMBER(18,0),
    ORDER_DATE      DATE,
    STARTDATE       DATE,
    ENDDATE         DATE,
    ISACTIVE        VARCHAR(10)
);

-- Create CUSTOMER_SCD2 table for SCD Type 2 tracking on customer dimension
-- Purpose: Maintains full history of customer attribute changes with effective date ranges
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMER_SCD2 (
    CUSTID          VARCHAR(50),
    NAME            VARCHAR(255),
    EMAILID         VARCHAR(255),
    REGION          VARCHAR(100),
    IS_CURRENT      BOOLEAN,
    EFFECTIVE_FROM  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO    TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ
);

-- Create ORDERSUMMARY table for joined customer-order data
-- Purpose: Stores denormalized join of customer and order data with computed total amount
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.ORDERSUMMARY (
    ORDERID         VARCHAR(50),
    CUSTID          VARCHAR(50),
    NAME            VARCHAR(255),
    EMAILID         VARCHAR(255),
    REGION          VARCHAR(100),
    ITEMNAME        VARCHAR(255),
    PRICEPERUNIT    NUMBER(18,2),
    QTY             NUMBER(18,0),
    TOTALAMOUNT     NUMBER(18,2),
    ORDER_DATE      DATE,
    STARTDATE       DATE,
    ENDDATE         DATE,
    ISACTIVE        VARCHAR(10)
);

-- Create CUSTOMERAGGREGATESPEND table for aggregated spending data
-- Purpose: Stores aggregated total spend per customer per order date for reporting
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND (
    NAME            VARCHAR(255),
    ORDER_DATE      DATE,
    TOTAL_SPEND     NUMBER(18,2)
);