/*==============================================================
Object Name    : 02_LOAD_STAGING_DATA
Purpose        : Load raw CSV data from Snowflake external stages
                 into CUSTOMER and ORDER base tables.
Generated By   : SDLC_DEVELOPER
Generated Date : 2025-01-24
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create file format for CSV ingestion
---------------------------------------------------------

-- Create CSV file format for data loading
-- Purpose: Define parsing rules for CSV files with headers, handling mismatched columns gracefully
CREATE FILE FORMAT IF NOT EXISTS IDEA_2_DB.PUBLIC.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL', 'null')
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Truncate and reload customer data from stage
---------------------------------------------------------

-- Truncate CUSTOMER table before fresh load
-- Purpose: Ensure idempotent full reload of customer data from source
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC.CUSTOMER;

-- Load customer data from stage into CUSTOMER table
-- Purpose: Ingest customer CSV data from the Snowflake stage into the base customer table
COPY INTO IDEA_2_DB.PUBLIC.CUSTOMER (CUSTID, NAME, EMAILID, REGION)
FROM @gen_ai_poc_snowflakecoe.sdlc_wizard_stage/customerdata
FILE_FORMAT = (
    FORMAT_NAME = 'IDEA_2_DB.PUBLIC.CSV_FORMAT'
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = CONTINUE;

---------------------------------------------------------
-- SECTION 3
-- Purpose: Truncate and reload order data from stage
---------------------------------------------------------

-- Truncate ORDER table before fresh load
-- Purpose: Ensure idempotent full reload of order data from source
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC."order";

-- Load order data from stage into ORDER table
-- Purpose: Ingest order CSV data from the Snowflake stage into the base order table
COPY INTO IDEA_2_DB.PUBLIC."order" (ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE)
FROM @gen_ai_poc_snowflakecoe.sdlc_wizard_stage/orderdata
FILE_FORMAT = (
    FORMAT_NAME = 'IDEA_2_DB.PUBLIC.CSV_FORMAT'
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = CONTINUE;