/*==============================================================
Object Name : ETL_RECONCILIATION_LOG
Purpose     : Reconciliation log table capturing per-run metrics
              for the aerospace parts pipeline including counts
              and execution status.
Generated By: SDLC_AGENT
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Set database and schema context
---------------------------------------------------------
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Create reconciliation log table for pipeline audit
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
    RUN_ID               VARCHAR(100),
    RUN_TIMESTAMP        TIMESTAMP_NTZ,
    SOURCE_COUNT         INTEGER,
    TARGET_COUNT         INTEGER,
    INSERTED_COUNT       INTEGER,
    UPDATED_COUNT        INTEGER,
    DECOMMISSIONED_COUNT INTEGER,
    EXCLUDED_COUNT       INTEGER,
    STATUS               VARCHAR(50)
);