/*==============================================================
Object Name    : 03_REMOVE_NULLS_AND_DUPLICATES
Purpose        : Cleanse CUSTOMER and ORDER tables by removing
                 records with null key fields and deduplicating
                 based on primary keys.
Generated By   : SDLC_DEVELOPER
Generated Date : 2025-01-24
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Remove null key records from CUSTOMER table
---------------------------------------------------------

-- Delete customer records with null CUSTID
-- Purpose: Remove records where the primary key CUSTID is null as they are invalid
DELETE FROM IDEA_2_DB.PUBLIC.CUSTOMER
WHERE CUSTID IS NULL;

-- Delete customer records with null NAME
-- Purpose: Remove records where NAME is null as customer name is a required field
DELETE FROM IDEA_2_DB.PUBLIC.CUSTOMER
WHERE NAME IS NULL;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Deduplicate CUSTOMER table keeping first occurrence
---------------------------------------------------------

-- Create temporary table with deduplicated customer records
-- Purpose: Use ROW_NUMBER to identify and retain only the first occurrence per CUSTID
CREATE OR REPLACE TEMPORARY TABLE IDEA_2_DB.PUBLIC.CUSTOMER_DEDUP AS
SELECT
    CUSTID,
    NAME,
    EMAILID,
    REGION
FROM IDEA_2_DB.PUBLIC.CUSTOMER
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTID ORDER BY NAME) = 1;

-- Truncate original CUSTOMER table
-- Purpose: Clear all records before reinserting deduplicated data
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC.CUSTOMER;

-- Insert deduplicated records back into CUSTOMER table
-- Purpose: Reload CUSTOMER with only unique records per CUSTID
INSERT INTO IDEA_2_DB.PUBLIC.CUSTOMER (CUSTID, NAME, EMAILID, REGION)
SELECT CUSTID, NAME, EMAILID, REGION
FROM IDEA_2_DB.PUBLIC.CUSTOMER_DEDUP;

---------------------------------------------------------
-- SECTION 3
-- Purpose: Remove null key records from ORDER table
---------------------------------------------------------

-- Delete order records with null ORDERID
-- Purpose: Remove records where the primary key ORDERID is null as they are invalid
DELETE FROM IDEA_2_DB.PUBLIC."order"
WHERE ORDERID IS NULL;

-- Delete order records with null CUSTID
-- Purpose: Remove records where CUSTID is null as the foreign key relationship is required
DELETE FROM IDEA_2_DB.PUBLIC."order"
WHERE CUSTID IS NULL;

---------------------------------------------------------
-- SECTION 4
-- Purpose: Deduplicate ORDER table keeping first occurrence
---------------------------------------------------------

-- Create temporary table with deduplicated order records
-- Purpose: Use ROW_NUMBER to identify and retain only the first occurrence per ORDERID
CREATE OR REPLACE TEMPORARY TABLE IDEA_2_DB.PUBLIC.ORDER_DEDUP AS
SELECT
    ORDERID,
    CUSTID,
    ITEMNAME,
    PRICEPERUNIT,
    QTY,
    ORDER_DATE,
    STARTDATE,
    ENDDATE,
    ISACTIVE
FROM IDEA_2_DB.PUBLIC."order"
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDERID ORDER BY ORDER_DATE DESC NULLS LAST) = 1;

-- Truncate original ORDER table
-- Purpose: Clear all records before reinserting deduplicated data
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC."order";

-- Insert deduplicated records back into ORDER table
-- Purpose: Reload ORDER with only unique records per ORDERID
INSERT INTO IDEA_2_DB.PUBLIC."order" (ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE)
SELECT ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE
FROM IDEA_2_DB.PUBLIC.ORDER_DEDUP;