/*==============================================================
Object Name    : 04_CREATE_ORDERSUMMARY_AND_JOIN
Purpose        : Join customer and order data on CUSTID and
                 populate the ORDERSUMMARY denormalized table
                 with computed TOTALAMOUNT.
Generated By   : SDLC_DEVELOPER
Generated Date : 2025-01-24
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Ensure ORDERSUMMARY table exists
---------------------------------------------------------

-- Create ORDERSUMMARY table if it does not already exist
-- Purpose: Ensure target table for joined customer-order data is available
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.ORDERSUMMARY (
    ORDERID         VARCHAR(50),
    CUSTID          VARCHAR(50),
    NAME            VARCHAR(255),
    EMAILID         VARCHAR(255),
    REGION          VARCHAR(100),
    ITEMNAME        VARCHAR(255),
    PRICEPERUNIT    NUMBER(18,2),
    QTY             NUMBER(18,0),
    TOTALAMOUNT     NUMBER(18,2),
    ORDER_DATE      DATE,
    STARTDATE       DATE,
    ENDDATE         DATE,
    ISACTIVE        VARCHAR(10)
);

---------------------------------------------------------
-- SECTION 2
-- Purpose: Truncate and reload ORDERSUMMARY with joined data
---------------------------------------------------------

-- Truncate ORDERSUMMARY before reload
-- Purpose: Ensure clean full reload of denormalized data each pipeline run
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC.ORDERSUMMARY;

-- Insert joined customer and order data into ORDERSUMMARY
-- Purpose: Denormalize customer attributes onto order records and compute TOTALAMOUNT as PRICEPERUNIT * QTY
INSERT INTO IDEA_2_DB.PUBLIC.ORDERSUMMARY (
    ORDERID,
    CUSTID,
    NAME,
    EMAILID,
    REGION,
    ITEMNAME,
    PRICEPERUNIT,
    QTY,
    TOTALAMOUNT,
    ORDER_DATE,
    STARTDATE,
    ENDDATE,
    ISACTIVE
)
SELECT
    O.ORDERID,
    O.CUSTID,
    C.NAME,
    C.EMAILID,
    C.REGION,
    O.ITEMNAME,
    O.PRICEPERUNIT,
    O.QTY,
    O.PRICEPERUNIT * O.QTY AS TOTALAMOUNT,
    O.ORDER_DATE,
    O.STARTDATE,
    O.ENDDATE,
    O.ISACTIVE
FROM IDEA_2_DB.PUBLIC."order" O
INNER JOIN IDEA_2_DB.PUBLIC.CUSTOMER C
    ON O.CUSTID = C.CUSTID;