/*==============================================================
Object Name    : 05_SCD2_CUSTOMER
Purpose        : Implement SCD Type 2 logic on CUSTOMER_SCD2
                 table to track full history of customer
                 attribute changes (NAME, EMAILID, REGION).
Generated By   : SDLC_DEVELOPER
Generated Date : 2025-01-24
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Ensure CUSTOMER_SCD2 table exists
---------------------------------------------------------

-- Create CUSTOMER_SCD2 table if it does not already exist
-- Purpose: Maintain slowly changing dimension type 2 history for customer records
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMER_SCD2 (
    CUSTID          VARCHAR(50),
    NAME            VARCHAR(255),
    EMAILID         VARCHAR(255),
    REGION          VARCHAR(100),
    IS_CURRENT      BOOLEAN,
    EFFECTIVE_FROM  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO    TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ
);

---------------------------------------------------------
-- SECTION 2
-- Purpose: Expire existing current records where attributes have changed
---------------------------------------------------------

-- Update existing current records to expire them when source attributes have changed
-- Purpose: Close out the current version of a customer record by setting IS_CURRENT=FALSE
--          and EFFECTIVE_TO to current timestamp when NAME, EMAILID, or REGION has changed
MERGE INTO IDEA_2_DB.PUBLIC.CUSTOMER_SCD2 AS TGT
USING (
    SELECT
        CUSTID,
        NAME,
        EMAILID,
        REGION
    FROM IDEA_2_DB.PUBLIC.CUSTOMER
) AS SRC
ON TGT.CUSTID = SRC.CUSTID
   AND TGT.IS_CURRENT = TRUE
WHEN MATCHED AND (
    NVL(TGT.NAME, '~~') <> NVL(SRC.NAME, '~~')
    OR NVL(TGT.EMAILID, '~~') <> NVL(SRC.EMAILID, '~~')
    OR NVL(TGT.REGION, '~~') <> NVL(SRC.REGION, '~~')
)
THEN UPDATE
    SET
        IS_CURRENT = FALSE,
        EFFECTIVE_TO = CURRENT_TIMESTAMP()
;

---------------------------------------------------------
-- SECTION 3
-- Purpose: Insert new current records for changed and new customers
---------------------------------------------------------

-- Insert new current version records for customers that changed or are brand new
-- Purpose: Add a new active row for any customer whose attributes changed (expired above)
--          or who does not yet exist in the SCD2 table
INSERT INTO IDEA_2_DB.PUBLIC.CUSTOMER_SCD2 (
    CUSTID,
    NAME,
    EMAILID,
    REGION,
    IS_CURRENT,
    EFFECTIVE_FROM,
    EFFECTIVE_TO
)
SELECT
    SRC.CUSTID,
    SRC.NAME,
    SRC.EMAILID,
    SRC.REGION,
    TRUE AS IS_CURRENT,
    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,
    '9999-12-31'::TIMESTAMP_NTZ AS EFFECTIVE_TO
FROM IDEA_2_DB.PUBLIC.CUSTOMER SRC
LEFT JOIN IDEA_2_DB.PUBLIC.CUSTOMER_SCD2 TGT
    ON SRC.CUSTID = TGT.CUSTID
    AND TGT.IS_CURRENT = TRUE
WHERE TGT.CUSTID IS NULL;