/*==============================================================
Object Name    : 06_AGGREGATE_SPEND
Purpose        : Aggregate total spend from ORDERSUMMARY grouped
                 by customer NAME and ORDER_DATE, and load into
                 CUSTOMERAGGREGATESPEND table.
Generated By   : SDLC_DEVELOPER
Generated Date : 2025-01-24
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Ensure CUSTOMERAGGREGATESPEND table exists
---------------------------------------------------------

-- Create CUSTOMERAGGREGATESPEND table if it does not already exist
-- Purpose: Store aggregated customer spending data for downstream reporting
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND (
    NAME            VARCHAR(255),
    ORDER_DATE      DATE,
    TOTAL_SPEND     NUMBER(18,2)
);

---------------------------------------------------------
-- SECTION 2
-- Purpose: Truncate and reload aggregated spend data
---------------------------------------------------------

-- Truncate CUSTOMERAGGREGATESPEND before reload
-- Purpose: Ensure clean full reload of aggregated data each pipeline run
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND;

-- Insert aggregated spend data grouped by NAME and ORDER_DATE
-- Purpose: Sum TOTALAMOUNT from ORDERSUMMARY per customer name and order date for reporting
INSERT INTO IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND (
    NAME,
    ORDER_DATE,
    TOTAL_SPEND
)
SELECT
    NAME,
    ORDER_DATE,
    SUM(TOTALAMOUNT) AS TOTAL_SPEND
FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY
WHERE NAME IS NOT NULL
  AND ORDER_DATE IS NOT NULL
GROUP BY NAME, ORDER_DATE
ORDER BY NAME, ORDER_DATE;