/*==============================================================
Object Name    : 07_CREATE_ERROR_LOG
Purpose        : Create error logging table and provide utility
                 statements for pipeline error tracking and
                 data validation checks.
Generated By   : SDLC_DEVELOPER
Generated Date : 2025-01-24
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create error log table for pipeline monitoring
---------------------------------------------------------

-- Create ERROR_LOG table for capturing pipeline errors
-- Purpose: Centralized error logging table to record failures during data pipeline execution
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.ERROR_LOG (
    ERROR_ID        NUMBER AUTOINCREMENT,
    ERROR_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PIPELINE_STEP   VARCHAR(255),
    ERROR_MESSAGE   VARCHAR(4000),
    ERROR_DETAIL    VARCHAR(4000),
    RECORD_COUNT    NUMBER(18,0)
);

---------------------------------------------------------
-- SECTION 2
-- Purpose: Data validation checks and integrity logging
---------------------------------------------------------

-- Validate: Check for orphan orders (orders without matching customers)
-- Purpose: Identify referential integrity issues between ORDER and CUSTOMER tables and log count
INSERT INTO IDEA_2_DB.PUBLIC.ERROR_LOG (PIPELINE_STEP, ERROR_MESSAGE, ERROR_DETAIL, RECORD_COUNT)
SELECT
    'DATA_VALIDATION' AS PIPELINE_STEP,
    'ORPHAN_ORDERS_DETECTED' AS ERROR_MESSAGE,
    'Orders exist with CUSTID not found in CUSTOMER table' AS ERROR_DETAIL,
    COUNT(*) AS RECORD_COUNT
FROM IDEA_2_DB.PUBLIC."order" O
LEFT JOIN IDEA_2_DB.PUBLIC.CUSTOMER C
    ON O.CUSTID = C.CUSTID
WHERE C.CUSTID IS NULL
HAVING COUNT(*) > 0;

-- Validate: Check for duplicate CUSTID in CUSTOMER table after cleansing
-- Purpose: Confirm deduplication was successful; log if duplicates still remain
INSERT INTO IDEA_2_DB.PUBLIC.ERROR_LOG (PIPELINE_STEP, ERROR_MESSAGE, ERROR_DETAIL, RECORD_COUNT)
SELECT
    'DATA_VALIDATION' AS PIPELINE_STEP,
    'DUPLICATE_CUSTID_DETECTED' AS ERROR_MESSAGE,
    'Duplicate CUSTID values found in CUSTOMER table after dedup' AS ERROR_DETAIL,
    COUNT(*) AS RECORD_COUNT
FROM (
    SELECT CUSTID
    FROM IDEA_2_DB.PUBLIC.CUSTOMER
    GROUP BY CUSTID
    HAVING COUNT(*) > 1
)
HAVING COUNT(*) > 0;

-- Validate: Check for duplicate ORDERID in ORDER table after cleansing
-- Purpose: Confirm deduplication was successful; log if duplicates still remain
INSERT INTO IDEA_2_DB.PUBLIC.ERROR_LOG (PIPELINE_STEP, ERROR_MESSAGE, ERROR_DETAIL, RECORD_COUNT)
SELECT
    'DATA_VALIDATION' AS PIPELINE_STEP,
    'DUPLICATE_ORDERID_DETECTED' AS ERROR_MESSAGE,
    'Duplicate ORDERID values found in ORDER table after dedup' AS ERROR_DETAIL,
    COUNT(*) AS RECORD_COUNT
FROM (
    SELECT ORDERID
    FROM IDEA_2_DB.PUBLIC."order"
    GROUP BY ORDERID
    HAVING COUNT(*) > 1
)
HAVING COUNT(*) > 0;

-- Validate: Check ORDERSUMMARY row count matches expected join result
-- Purpose: Ensure the join produced the expected number of records
INSERT INTO IDEA_2_DB.PUBLIC.ERROR_LOG (PIPELINE_STEP, ERROR_MESSAGE, ERROR_DETAIL, RECORD_COUNT)
SELECT
    'DATA_VALIDATION' AS PIPELINE_STEP,
    'ORDERSUMMARY_COUNT_CHECK' AS ERROR_MESSAGE,
    'Row count in ORDERSUMMARY: ' || CAST(COUNT(*) AS VARCHAR) AS ERROR_DETAIL,
    COUNT(*) AS RECORD_COUNT
FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY;

-- Validate: Check CUSTOMERAGGREGATESPEND has data
-- Purpose: Ensure aggregation produced results for downstream consumption
INSERT INTO IDEA_2_DB.PUBLIC.ERROR_LOG (PIPELINE_STEP, ERROR_MESSAGE, ERROR_DETAIL, RECORD_COUNT)
SELECT
    'DATA_VALIDATION' AS PIPELINE_STEP,
    'AGGREGATE_SPEND_COUNT_CHECK' AS ERROR_MESSAGE,
    'Row count in CUSTOMERAGGREGATESPEND: ' || CAST(COUNT(*) AS VARCHAR) AS ERROR_DETAIL,
    COUNT(*) AS RECORD_COUNT
FROM IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND;