/*==============================================================
Object Name : AEROSPACE_PARTS_SOURCE
Purpose     : Source staging table for aerospace parts inventory
              data ingested prior to transformation and loading.
Generated By: SDLC_AGENT
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Set database and schema context
---------------------------------------------------------
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Create source staging table for aerospace parts
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE (
    PART_NUMBER          VARCHAR(100),
    MANUFACTURER         VARCHAR(255),
    WEIGHT_KG            FLOAT,
    UNIT_PRICE_USD       FLOAT,
    LIFECYCLE_STATUS     VARCHAR(100),
    INSTALLATION_DATE    DATE,
    CERTIFICATION_STATUS VARCHAR(100),
    LEAD_TIME_DAYS       INTEGER,
    UPDATED_AT           TIMESTAMP_NTZ
);