/*==============================================================
Object Name : SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Stored procedure implementing the full incremental
              SCD Type 1 pipeline for aerospace parts inventory:
              watermark-based incremental load, deduplication,
              transformations, exclusion filters, RISK_SCORE
              derivation, SCD1 MERGE, soft delete, and
              reconciliation logging to ETL_RECONCILIATION_LOG.
Generated By: SDLC_AGENT
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Set database and schema context
---------------------------------------------------------
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Create or replace the main pipeline stored procedure
---------------------------------------------------------
CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_run_id               VARCHAR;
    v_run_timestamp        TIMESTAMP_NTZ;
    v_watermark            TIMESTAMP_NTZ;
    v_source_count         INTEGER;
    v_excluded_count       INTEGER;
    v_inserted_count       INTEGER;
    v_updated_count        INTEGER;
    v_decommissioned_count INTEGER;
    v_target_count         INTEGER;
    v_status               VARCHAR;
    v_error_message        VARCHAR;
BEGIN

    ---------------------------------------------------------
    -- SECTION 3
    -- Purpose: Initialise run metadata and watermark
    ---------------------------------------------------------
    v_run_id        := 'RUN_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS') || '_' || UNIFORM(1000, 9999, RANDOM())::VARCHAR;
    v_run_timestamp := CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    v_status        := 'SUCCESS';

    -- Determine watermark: use MAX(RUN_TIMESTAMP) from last successful run
    -- If no prior successful run exists, perform full load (watermark = epoch)
    SELECT COALESCE(MAX(RUN_TIMESTAMP), '1970-01-01 00:00:00'::TIMESTAMP_NTZ)
    INTO   v_watermark
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    WHERE  STATUS = 'SUCCESS';

    ---------------------------------------------------------
    -- SECTION 4
    -- Purpose: Create transient staging table for deduplicated
    --          and transformed incremental source records
    ---------------------------------------------------------
    CREATE OR REPLACE TRANSIENT TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_STAGE_WORK AS
    WITH RAW_INCREMENTAL AS (
        SELECT
            PART_NUMBER,
            MANUFACTURER,
            WEIGHT_KG,
            UNIT_PRICE_USD,
            LIFECYCLE_STATUS,
            INSTALLATION_DATE,
            CERTIFICATION_STATUS,
            LEAD_TIME_DAYS,
            UPDATED_AT
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE UPDATED_AT > v_watermark
    ),
    DEDUPED AS (
        SELECT
            PART_NUMBER,
            MANUFACTURER,
            WEIGHT_KG,
            UNIT_PRICE_USD,
            LIFECYCLE_STATUS,
            INSTALLATION_DATE,
            CERTIFICATION_STATUS,
            LEAD_TIME_DAYS,
            UPDATED_AT,
            ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN
        FROM RAW_INCREMENTAL
        QUALIFY ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) = 1
    ),
    TRANSFORMED AS (
        SELECT
            PART_NUMBER,
            INITCAP(MANUFACTURER)                                          AS MANUFACTURER,
            CASE WHEN WEIGHT_KG <= 0 THEN NULL ELSE WEIGHT_KG END         AS WEIGHT_KG,
            ROUND(UNIT_PRICE_USD, 2)                                       AS UNIT_PRICE_USD,
            LIFECYCLE_STATUS,
            INSTALLATION_DATE,
            CERTIFICATION_STATUS,
            LEAD_TIME_DAYS,
            UPDATED_AT
        FROM DEDUPED
    ),
    FILTERED AS (
        SELECT
            PART_NUMBER,
            MANUFACTURER,
            WEIGHT_KG,
            UNIT_PRICE_USD,
            LIFECYCLE_STATUS,
            INSTALLATION_DATE,
            CERTIFICATION_STATUS,
            LEAD_TIME_DAYS,
            UPDATED_AT
        FROM TRANSFORMED
        WHERE NOT (
            LIFECYCLE_STATUS = 'End of Life'
            AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE())
        )
    ),
    RISK_SCORED AS (
        SELECT
            PART_NUMBER,
            MANUFACTURER,
            WEIGHT_KG,
            UNIT_PRICE_USD,
            LIFECYCLE_STATUS,
            INSTALLATION_DATE,
            CERTIFICATION_STATUS,
            LEAD_TIME_DAYS,
            UPDATED_AT,
            CASE
                WHEN UPPER(CERTIFICATION_STATUS) = 'PENDING'
                     AND LEAD_TIME_DAYS > 90
                    THEN 'High Risk'
                WHEN UPPER(CERTIFICATION_STATUS) = 'PENDING'
                     OR  LEAD_TIME_DAYS > 120
                    THEN 'Medium Risk'
                WHEN UPPER(CERTIFICATION_STATUS) IN ('FAA', 'EASA', 'DUAL')
                     AND LEAD_TIME_DAYS <= 60
                    THEN 'Low Risk'
                ELSE 'Medium Risk'
            END AS RISK_SCORE
        FROM FILTERED
    )
    SELECT
        PART_NUMBER,
        MANUFACTURER,
        WEIGHT_KG,
        UNIT_PRICE_USD,
        LIFECYCLE_STATUS,
        INSTALLATION_DATE,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,
        UPDATED_AT,
        RISK_SCORE
    FROM RISK_SCORED;

    ---------------------------------------------------------
    -- SECTION 5
    -- Purpose: Capture source count (incremental batch size)
    --          and excluded count for reconciliation
    ---------------------------------------------------------
    SELECT COUNT(*)
    INTO   v_source_count
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    WHERE  UPDATED_AT > v_watermark;

    SELECT (v_source_count - COUNT(*))
    INTO   v_excluded_count
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_STAGE_WORK;

    ---------------------------------------------------------
    -- SECTION 6
    -- Purpose: SCD Type 1 MERGE into AEROSPACE_PARTS_TARGET
    --          Inserts new records, updates existing records
    ---------------------------------------------------------
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS TGT
    USING GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_STAGE_WORK AS SRC
    ON TGT.PART_NUMBER = SRC.PART_NUMBER
    WHEN MATCHED THEN
        UPDATE SET
            TGT.MANUFACTURER         = SRC.MANUFACTURER,
            TGT.WEIGHT_KG            = SRC.WEIGHT_KG,
            TGT.UNIT_PRICE_USD       = SRC.UNIT_PRICE_USD,
            TGT.LIFECYCLE_STATUS     = SRC.LIFECYCLE_STATUS,
            TGT.INSTALLATION_DATE    = SRC.INSTALLATION_DATE,
            TGT.CERTIFICATION_STATUS = SRC.CERTIFICATION_STATUS,
            TGT.LEAD_TIME_DAYS       = SRC.LEAD_TIME_DAYS,
            TGT.UPDATED_AT           = SRC.UPDATED_AT,
            TGT.RISK_SCORE           = SRC.RISK_SCORE,
            TGT.RECORD_STATUS        = 'Active',
            TGT.LOAD_TIMESTAMP       = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
            TGT.PIPELINE_RUN_ID      = v_run_id
    WHEN NOT MATCHED THEN
        INSERT (
            PART_NUMBER,
            MANUFACTURER,
            WEIGHT_KG,
            UNIT_PRICE_USD,
            LIFECYCLE_STATUS,
            INSTALLATION_DATE,
            CERTIFICATION_STATUS,
            LEAD_TIME_DAYS,
            UPDATED_AT,
            RISK_SCORE,
            RECORD_STATUS,
            LOAD_TIMESTAMP,
            PIPELINE_RUN_ID
        )
        VALUES (
            SRC.PART_NUMBER,
            SRC.MANUFACTURER,
            SRC.WEIGHT_KG,
            SRC.UNIT_PRICE_USD,
            SRC.LIFECYCLE_STATUS,
            SRC.INSTALLATION_DATE,
            SRC.CERTIFICATION_STATUS,
            SRC.LEAD_TIME_DAYS,
            SRC.UPDATED_AT,
            SRC.RISK_SCORE,
            'Active',
            CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
            v_run_id
        );

    ---------------------------------------------------------
    -- SECTION 7
    -- Purpose: Capture inserted and updated counts from MERGE
    --          using post-merge target state comparison
    ---------------------------------------------------------
    SELECT
        SUM(CASE WHEN PIPELINE_RUN_ID = v_run_id AND LOAD_TIMESTAMP >= v_run_timestamp THEN 1 ELSE 0 END)
    INTO v_inserted_count
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    WHERE PIPELINE_RUN_ID = v_run_id
      AND RECORD_STATUS   = 'Active';

    -- Updated count = records in stage that already existed in target (matched rows)
    SELECT COUNT(*)
    INTO   v_updated_count
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_STAGE_WORK SRC
    INNER JOIN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET TGT
        ON SRC.PART_NUMBER = TGT.PART_NUMBER
    WHERE TGT.PIPELINE_RUN_ID = v_run_id
      AND TGT.RECORD_STATUS   = 'Active';

    -- Adjust: inserted = total touched this run minus updated
    v_inserted_count := v_inserted_count - v_updated_count;
    IF (v_inserted_count < 0) THEN
        v_inserted_count := 0;
    END IF;

    ---------------------------------------------------------
    -- SECTION 8
    -- Purpose: Soft delete — mark target records as
    --          Decommissioned when absent from current source batch
    ---------------------------------------------------------
    UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS TGT
    SET
        TGT.RECORD_STATUS   = 'Decommissioned',
        TGT.LOAD_TIMESTAMP  = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
        TGT.PIPELINE_RUN