/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_TARGET
Purpose     : SCD Type 1 analytics-ready target table for aerospace parts inventory
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-13
=========================================================*/

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET (
    PART_NUMBER             VARCHAR(100)    NOT NULL,
    MANUFACTURER            VARCHAR(255),
    WEIGHT_KG               NUMBER(10,3),
    UNIT_PRICE_USD          NUMBER(15,2),
    LIFECYCLE_STATUS        VARCHAR(100),
    INSTALLATION_DATE       DATE,
    CERTIFICATION_STATUS    VARCHAR(50),
    LEAD_TIME_DAYS          NUMBER(6,0),
    RISK_SCORE              VARCHAR(20),
    IS_DELETED              BOOLEAN         DEFAULT FALSE,
    UPDATED_AT              TIMESTAMP_NTZ,
    DW_INSERT_TS            TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATE_TS            TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

-- SECTION 2: Constraints
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    ADD CONSTRAINT PK_APT_TARGET PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- SCD Type 1: updates overwrite existing records on PART_NUMBER match.
-- RISK_SCORE: High Risk | Medium Risk | Low Risk derived in SP.
-- IS_DELETED = TRUE indicates soft-deleted (Decommissioned) records.
-- MANUFACTURER stored in CamelCase (INITCAP applied in SP).