/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_SOURCE
Purpose     : Source/staging table for aerospace parts inventory raw ingestion
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-13
=========================================================*/

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE (
    PART_NUMBER             VARCHAR(100)    NOT NULL,
    MANUFACTURER            VARCHAR(255),
    WEIGHT_KG               NUMBER(10,3),
    UNIT_PRICE_USD          NUMBER(15,2),
    LIFECYCLE_STATUS        VARCHAR(100),
    INSTALLATION_DATE       DATE,
    CERTIFICATION_STATUS    VARCHAR(50),
    LEAD_TIME_DAYS          NUMBER(6,0),
    UPDATED_AT              TIMESTAMP_NTZ,
    SOURCE_SYSTEM           VARCHAR(100),
    LOAD_TIMESTAMP          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

-- SECTION 2: Constraints
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    ADD CONSTRAINT PK_APS_SOURCE PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- Incremental loads use UPDATED_AT for watermark-based filtering.
-- Deduplication retains latest UPDATED_AT per PART_NUMBER before merge.
-- LIFECYCLE_STATUS = 'End of Life' with INSTALLATION_DATE > 3 years old are excluded.