/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : Pipeline audit and reconciliation log for aerospace parts ELT runs
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-13
=========================================================*/

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
    RUN_ID                  VARCHAR(36)     NOT NULL,
    RUN_TIMESTAMP           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    LOAD_TYPE               VARCHAR(20),
    SOURCE_COUNT            NUMBER(12,0),
    EXCLUDED_COUNT          NUMBER(12,0),
    INSERTED_COUNT          NUMBER(12,0),
    UPDATED_COUNT           NUMBER(12,0),
    SOFT_DELETED_COUNT      NUMBER(12,0),
    TARGET_COUNT_POST_LOAD  NUMBER(12,0),
    STATUS                  VARCHAR(20),
    ERROR_MESSAGE           VARCHAR(4000),
    EXECUTION_TIME_SECS     NUMBER(10,3),
    WATERMARK_FROM          TIMESTAMP_NTZ,
    WATERMARK_TO            TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    ADD CONSTRAINT PK_ETL_RECON PRIMARY KEY (RUN_ID);

-- SECTION 3: Notes
-- One row inserted per pipeline execution.
-- STATUS values: SUCCESS | FAILED | PARTIAL.
-- LOAD_TYPE values: INCREMENTAL | FULL.