/*=========================================================
Object Name : QA_AEROSPACE_PARTS_PIPELINE
Purpose     : QA acceptance criteria queries AC-001 through AC-010
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-13
=========================================================*/

-- DATABASE  : GEN_AI_POC_SNOWFLAKECOE
-- SCHEMA    : SDLC_WIZARD
-- WAREHOUSE : SNOWFLAKE_LEARNING_WH
-- PASS CRITERIA: All queries return PASS or zero violation rows.

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- ============================================================
-- AC-001 | No duplicate PART_NUMBER in target
-- PASS: zero violation rows
-- ============================================================
SELECT 'AC-001' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM (
    SELECT PART_NUMBER
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    GROUP BY PART_NUMBER
    HAVING COUNT(*) > 1
) D;

-- ============================================================
-- AC-002 | WEIGHT_KG has no zero or negative values
-- PASS: zero violation rows
-- ============================================================
SELECT 'AC-002' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE WEIGHT_KG IS NOT NULL
  AND WEIGHT_KG <= 0;

-- ============================================================
-- AC-003 | UNIT_PRICE_USD rounded to 2 decimal places
-- PASS: zero violation rows
-- ============================================================
SELECT 'AC-003' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE UNIT_PRICE_USD <> ROUND(UNIT_PRICE_USD, 2);

-- ============================================================
-- AC-004 | MANUFACTURER stored in INITCAP format
-- PASS: zero violation rows
-- ============================================================
SELECT 'AC-004' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE MANUFACTURER IS NOT NULL
  AND MANUFACTURER <> INITCAP(MANUFACTURER);

-- ============================================================
-- AC-005 | End-of-Life parts older than 3 years excluded
-- PASS: zero violation rows
-- ============================================================
SELECT 'AC-005' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE LIFECYCLE_STATUS = 'End of Life'
  AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE());

-- ============================================================
-- AC-006 | RISK_SCORE only contains valid values
-- PASS: zero violation rows
-- ============================================================
SELECT 'AC-006' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE RISK_SCORE NOT IN ('High Risk', 'Medium Risk', 'Low Risk');

-- ============================================================
-- AC-007 | High Risk: CERTIFICATION_STATUS=Pending AND LEAD_TIME_DAYS>90
-- PASS: zero violation rows (no misclassified High Risk)
-- ============================================================
SELECT 'AC-007' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE RISK_SCORE = 'High Risk'
  AND NOT (CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 90);

-- ============================================================
-- AC-008 | Low Risk: CERTIFICATION_STATUS IN (FAA/EASA/Dual) AND LEAD_TIME_DAYS<=60
-- PASS: zero violation rows (no misclassified Low Risk)
-- ============================================================
SELECT 'AC-008' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE RISK_SCORE = 'Low Risk'
  AND NOT (CERTIFICATION_STATUS IN ('FAA', 'EASA', 'Dual') AND LEAD_TIME_DAYS <= 60);

-- ============================================================
-- AC-009 | Soft-deleted parts have IS_DELETED = TRUE
-- PASS: zero violation rows
-- ============================================================
SELECT 'AC-009' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE LIFECYCLE_STATUS = 'Decommissioned'
  AND (IS_DELETED IS NULL OR IS_DELETED = FALSE);

-- ============================================================
-- AC-010 | ETL_RECONCILIATION_LOG has at least one entry per run
-- PASS: at least one log row exists for today
-- ============================================================
SELECT 'AC-010' AS CRITERIA,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS LOG_ROWS_TODAY
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
WHERE CAST(RUN_TIMESTAMP AS DATE) = CURRENT_DATE();