/*=========================================================
Object Name : SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : SCD Type 1 ELT stored procedure for aerospace parts inventory pipeline
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-13
=========================================================*/

-- SECTION 1: Object Definition
CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1(
    P_LOAD_TYPE VARCHAR  -- 'INCREMENTAL' or 'FULL'
)
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
var run_id        = Math.random().toString(36).substring(2,10).toUpperCase()
                  + '-' + Date.now();
var run_ts        = new Date().toISOString();
var start_ms      = Date.now();
var status        = 'SUCCESS';
var err_msg       = '';
var src_count     = 0, excl_count = 0, ins_count = 0;
var upd_count     = 0, del_count  = 0, tgt_post  = 0;
var wm_from       = 'NULL', wm_to = 'NULL';

try {
    // Step 1: Watermark for incremental
    var wm_sql = '';
    if (P_LOAD_TYPE === 'INCREMENTAL') {
        var wm_res = snowflake.execute({
            sqlText: `SELECT COALESCE(MAX(WATERMARK_TO), '1900-01-01'::TIMESTAMP_NTZ)
                      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
                      WHERE STATUS = 'SUCCESS'`
        });
        wm_res.next();
        wm_from = "'" + wm_res.getColumnValue(1) + "'";
        var wm_to_res = snowflake.execute({
            sqlText: `SELECT MAX(UPDATED_AT) FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE`
        });
        wm_to_res.next();
        wm_to = "'" + wm_to_res.getColumnValue(1) + "'";
        wm_sql = `AND UPDATED_AT > ${wm_from} AND UPDATED_AT <= ${wm_to}`;
    }

    // Step 2: Build deduplicated + transformed staging CTE and merge
    var merge_sql = `
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET T
    USING (
        WITH DEDUPED AS (
            SELECT *,
                   ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN
            FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
            WHERE 1=1 ${wm_sql}
        ),
        FILTERED AS (
            SELECT
                PART_NUMBER,
                INITCAP(MANUFACTURER)                          AS MANUFACTURER,
                CASE WHEN WEIGHT_KG <= 0 THEN NULL
                     ELSE WEIGHT_KG END                        AS WEIGHT_KG,
                ROUND(UNIT_PRICE_USD, 2)                       AS UNIT_PRICE_USD,
                LIFECYCLE_STATUS,
                INSTALLATION_DATE,
                CERTIFICATION_STATUS,
                LEAD_TIME_DAYS,
                UPDATED_AT,
                CASE
                    WHEN CERTIFICATION_STATUS = 'Pending'
                         AND LEAD_TIME_DAYS > 90              THEN 'High Risk'
                    WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual')
                         AND LEAD_TIME_DAYS <= 60             THEN 'Low Risk'
                    WHEN CERTIFICATION_STATUS = 'Pending'
                         OR  LEAD_TIME_DAYS > 120             THEN 'Medium Risk'
                    ELSE 'Medium Risk'
                END                                            AS RISK_SCORE
            FROM DEDUPED
            WHERE RN = 1