/*=========================================================
Object Name : DDL_TASK_AEROSPACE_PARTS
Purpose     : Snowflake Task to schedule SP_LOAD_AEROSPACE_PARTS_SCD1 daily at 02:00 UTC
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-13
=========================================================*/

-- SECTION 1: Object Definition
CREATE OR REPLACE TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_AEROSPACE_PARTS_DAILY
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 2 * * * UTC'
    COMMENT   = 'Daily ELT load for aerospace parts SCD1 pipeline at 02:00 UTC'
AS
    CALL GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1('INCREMENTAL');

-- SECTION 2: Constraints
ALTER TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_AEROSPACE_PARTS_DAILY RESUME;

-- SECTION 3: Notes
-- Pass 'FULL' instead of 'INCREMENTAL' for full reload runs.
-- Task must be RESUMED after creation; SUSPENDED by default in Snowflake.
-- SLA: 1 million records must complete within 5 minutes.