/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_SOURCE
Purpose     : Source/staging table for aerospace parts inventory raw ingestion
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE (
    PART_NUMBER         VARCHAR(100)    NOT NULL,
    MANUFACTURER        VARCHAR(255),
    WEIGHT_KG           NUMBER(10,3),
    UNIT_PRICE_USD      NUMBER(15,2),
    LIFECYCLE_STATUS    VARCHAR(100),
    INSTALLATION_DATE   DATE,
    CERTIFICATION       VARCHAR(100),
    LEAD_TIME_DAYS      NUMBER(6),
    UPDATED_AT          TIMESTAMP_NTZ,
    CREATED_AT          TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    ADD CONSTRAINT PK_APS_PART_NUMBER PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- Raw ingestion layer; no transformations applied at this stage.
-- UPDATED_AT drives incremental load logic in SP_LOAD_AEROSPACE_PARTS_SCD1.
-- CERTIFICATION valid values: FAA, EASA, Dual, Certification Pending.