/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : Pipeline audit and reconciliation log for aerospace parts ETL runs
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
    RUN_ID                  VARCHAR(36)     NOT NULL,
    RUN_TIMESTAMP           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    LOAD_TYPE               VARCHAR(20),
    SOURCE_COUNT            NUMBER,
    TARGET_COUNT_BEFORE     NUMBER,
    TARGET_COUNT_AFTER      NUMBER,
    INSERTED_COUNT          NUMBER,
    UPDATED_COUNT           NUMBER,
    DELETED_COUNT           NUMBER,
    EXCLUDED_COUNT          NUMBER,
    LAST_RUN_TIMESTAMP      TIMESTAMP_NTZ,
    STATUS                  VARCHAR(20),
    ERROR_MESSAGE           VARCHAR(4000),
    EXECUTION_TIME_SECS     NUMBER(10,2)
);

-- SECTION 2: Constraints
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    ADD CONSTRAINT PK_ERL_RUN_ID PRIMARY KEY (RUN_ID);

-- SECTION 3: Notes
-- One row inserted per SP execution regardless of success or failure.
-- LOAD_TYPE: FULL or INCREMENTAL.
-- STATUS: SUCCESS or FAILED.
-- EXECUTION_TIME_SECS measures wall-clock duration of the SP run.