/*=========================================================
Object Name : QA_AEROSPACE_PARTS_PIPELINE
Purpose     : QA acceptance criteria queries AC-001 through AC-010
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

-- DATABASE  : GEN_AI_POC_SNOWFLAKECOE
-- SCHEMA    : SDLC_WIZARD
-- WAREHOUSE : SNOWFLAKE_LEARNING_WH
-- PASS CRITERIA: All queries return PASS or zero violation rows.

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- ============================================================
-- AC-001 | No duplicate PART_NUMBER in target
-- PASS: zero rows returned
-- ============================================================
SELECT 'AC-001' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM (
    SELECT PART_NUMBER
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    GROUP BY PART_NUMBER
    HAVING COUNT(*) > 1
) DUPES;

-- ============================================================
-- AC-002 | WEIGHT_KG has no zero or negative values (replaced with NULL)
-- PASS: zero rows returned
-- ============================================================
SELECT 'AC-002' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE WEIGHT_KG <= 0;

-- ============================================================
-- AC-003 | UNIT_PRICE_USD rounded to 2 decimal places
-- PASS: zero rows returned
-- ============================================================
SELECT 'AC-003' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE UNIT_PRICE_USD <> ROUND(UNIT_PRICE_USD, 2);

-- ============================================================
-- AC-004 | No End of Life records with INSTALLATION_DATE older than 3 years
-- PASS: zero rows returned
-- ============================================================
SELECT 'AC-004' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE LIFECYCLE_STATUS = 'End of Life'
  AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE());

-- ============================================================
-- AC-005 | RISK_SCORE only contains valid values
-- PASS: zero rows returned
-- ============================================================
SELECT 'AC-005' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE RISK_SCORE NOT IN ('High Risk', 'Medium Risk', 'Low Risk');

-- ============================================================
-- AC-006 | High Risk logic: Certification Pending AND LEAD_TIME_DAYS > 90
-- PASS: zero rows returned (no misclassified High Risk records)
-- ============================================================
SELECT 'AC-006' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE RISK_SCORE = 'High Risk'
  AND NOT (CERTIFICATION_STATUS = 'Certification Pending' AND LEAD_TIME_DAYS > 90);

-- ============================================================
-- AC-007 | Low Risk logic: Certification IN (FAA, EASA, Dual) AND LEAD_TIME_DAYS <= 60
-- PASS: zero rows returned (no misclassified Low Risk records)
-- ============================================================
SELECT 'AC-007' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE RISK_SCORE = 'Low Risk'
  AND NOT (CERTIFICATION_STATUS IN ('FAA', 'EASA', 'Dual') AND LEAD_TIME_DAYS <= 60);

-- ============================================================
-- AC-008 | Soft delete: records missing from source marked Decommissioned
-- PASS: zero active target records absent from source without Decommissioned status
-- ============================================================
SELECT 'AC-008' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET T
WHERE NOT EXISTS (
    SELECT 1
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE S
    WHERE S.PART_NUMBER = T.PART_NUMBER
)
AND T.LIFECYCLE_STATUS <> 'Decommissioned';

-- ============================================================
-- AC-009 | ETL_RECONCILIATION_LOG has at least one entry per pipeline run
-- PASS: returns PASS when log has records
-- ============================================================
SELECT 'AC-009' AS CRITERIA,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS LOG_ENTRY_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
WHERE PROCEDURE_NAME = 'SP_LOAD_AEROSPACE_PARTS_SCD1';

-- ============================================================
-- AC-010 | MANUFACTURER stored in CamelCase (no all-uppercase values)
-- PASS: zero rows returned
-- ============================================================
SELECT 'AC-010' AS CRITERIA,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
       COUNT(*) AS VIOLATION_COUNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
WHERE MANUFACTURER = UPPER(MANUFACTURER)
  AND LENGTH(MANUFACTURER) > 1;