/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_TARGET
Purpose     : Target table DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS AEROSPACE_PARTS_TARGET (
    PART_NUMBER             VARCHAR(50)     NOT NULL,
    MANUFACTURER            VARCHAR(100),
    WEIGHT_KG               NUMBER(10,4),
    UNIT_PRICE_USD          NUMBER(14,2),
    LIFECYCLE_STATUS        VARCHAR(50),
    INSTALLATION_DATE       DATE,
    CERTIFICATION_STATUS    VARCHAR(50),
    LEAD_TIME_DAYS          NUMBER(6,0),
    UPDATED_AT              TIMESTAMP_NTZ,
    RISK_SCORE              VARCHAR(20),
    DW_INSERT_TIMESTAMP     TIMESTAMP_NTZ,
    DW_UPDATED_TIMESTAMP    TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
ALTER TABLE AEROSPACE_PARTS_TARGET
    ADD CONSTRAINT IF NOT EXISTS PK_APT_PART_NUMBER PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- RISK_SCORE  : High Risk | Medium Risk | Low Risk
-- SCD Type 1  : Full overwrite on PART_NUMBER match
-- Soft Delete : LIFECYCLE_STATUS set to Decommissioned when absent from source