/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : ETL reconciliation log DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS ETL_RECONCILIATION_LOG (
    RUN_ID                  VARCHAR(100)    NOT NULL,
    RUN_TIMESTAMP           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_COUNT            NUMBER(12,0),
    TARGET_COUNT_BEFORE     NUMBER(12,0),
    TARGET_COUNT_AFTER      NUMBER(12,0),
    INSERTED_COUNT          NUMBER(12,0),
    UPDATED_COUNT           NUMBER(12,0),
    SOFT_DELETED_COUNT      NUMBER(12,0),
    EXCLUDED_COUNT          NUMBER(12,0),
    STATUS                  VARCHAR(20),
    ERROR_MESSAGE           VARCHAR(4000)
);

-- SECTION 2: Constraints
ALTER TABLE ETL_RECONCILIATION_LOG
    ADD CONSTRAINT IF NOT EXISTS PK_ERL_RUN_ID PRIMARY KEY (RUN_ID);

-- SECTION 3: Notes
-- STATUS values : SUCCESS | FAILED | PARTIAL
-- RUN_ID        : UUID generated per execution
-- Mandatory     : Every SP execution must insert one row