/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_SOURCE
Purpose     : Source table DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS AEROSPACE_PARTS_SOURCE (
    PART_NUMBER         VARCHAR(50)     NOT NULL,
    MANUFACTURER        VARCHAR(100),
    WEIGHT_KG           NUMBER(10,4),
    UNIT_PRICE_USD      NUMBER(14,4),
    LIFECYCLE_STATUS    VARCHAR(50),
    INSTALLATION_DATE   DATE,
    CERTIFICATION_STATUS VARCHAR(50),
    LEAD_TIME_DAYS      NUMBER(6,0),
    UPDATED_AT          TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
ALTER TABLE AEROSPACE_PARTS_SOURCE
    ADD CONSTRAINT IF NOT EXISTS PK_APS_PART_NUMBER PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- Business Key : PART_NUMBER
-- Incremental  : UPDATED_AT drives delta detection
-- SCD Strategy : Type 1 (overwrite) on target