/*=========================================================
Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Schedule SP_LOAD_AEROSPACE_PARTS_SCD1 daily at 02:00 UTC
Database    : GEN_AI_POC_SNOWFLAKECOE
Schema      : SDLC_WIZARD
Warehouse   : SNOWFLAKE_LEARNING_WH
=========================================================*/

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

CREATE OR REPLACE TASK TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 2 * * * UTC'
AS
    CALL SP_LOAD_AEROSPACE_PARTS_SCD1();

ALTER TASK TASK_SP_LOAD_AEROSPACE_PARTS_SCD1 RESUME;