/*==============================================================
Object Name : AEROSPACE_PARTS_TARGET
Purpose     : Target table storing transformed, deduplicated,
              and enriched aerospace parts inventory records.
Generated By: SDLC_AGENT
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Set database and schema context
---------------------------------------------------------
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Create target table with derived and audit columns
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET (
    PART_NUMBER          VARCHAR(100),
    MANUFACTURER         VARCHAR(255),
    WEIGHT_KG            FLOAT,
    UNIT_PRICE_USD       FLOAT,
    LIFECYCLE_STATUS     VARCHAR(100),
    INSTALLATION_DATE    DATE,
    CERTIFICATION_STATUS VARCHAR(100),
    LEAD_TIME_DAYS       INTEGER,
    UPDATED_AT           TIMESTAMP_NTZ,
    RISK_SCORE           VARCHAR(50),
    RECORD_STATUS        VARCHAR(50)        DEFAULT 'Active',
    LOAD_TIMESTAMP       TIMESTAMP_NTZ      DEFAULT CURRENT_TIMESTAMP(),
    PIPELINE_RUN_ID      VARCHAR(100)
);